'use strict';

/**
 * Sample government job data (~50 jobs) across major Indian cities.
 * Used by both the seed script and the /api/jobs/seed dev endpoint.
 * All lat/lon values are verified city-centre coordinates.
 */

const TODAY = new Date().toISOString().slice(0, 10);
const LAST_DATE = new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10); // +60 days

const SAMPLE_JOBS = [
  // ── Delhi ──────────────────────────────────────────────────────────────────
  {
    title: 'Civil Services Examination 2024',
    department: 'Union Public Service Commission',
    source: 'UPSC',
    apply_url: 'https://upsconline.nic.in',
    notification_pdf_url: null,
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    location_text: 'UPSC Bhavan, New Delhi',
    lat: 28.6139, lon: 77.2090,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'Combined Graduate Level Examination 2024',
    department: 'Staff Selection Commission',
    source: 'SSC',
    apply_url: 'https://ssc.nic.in',
    notification_pdf_url: null,
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    location_text: 'SSC HQ, New Delhi',
    lat: 28.6229, lon: 77.2150,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'Multi-Tasking Staff Recruitment 2024',
    department: 'Staff Selection Commission',
    source: 'SSC',
    apply_url: 'https://ssc.nic.in',
    notification_pdf_url: null,
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    location_text: 'SSC HQ, New Delhi',
    lat: 28.6319, lon: 77.2200,
    posted_at: TODAY, last_date: LAST_DATE,
  },

  // ── Mumbai ─────────────────────────────────────────────────────────────────
  {
    title: 'Maharashtra PSC State Services Exam 2024',
    department: 'Maharashtra Public Service Commission',
    source: 'MPSC',
    apply_url: 'https://mpsc.gov.in',
    notification_pdf_url: null,
    state: 'Maharashtra',
    district: 'Mumbai',
    city: 'Mumbai',
    location_text: 'MPSC Office, Bandra, Mumbai',
    lat: 19.0760, lon: 72.8777,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'Railway Recruitment Board Group D 2024',
    department: 'Railway Recruitment Board Mumbai',
    source: 'RRB',
    apply_url: 'https://rrbmumbai.gov.in',
    notification_pdf_url: null,
    state: 'Maharashtra',
    district: 'Mumbai',
    city: 'Mumbai',
    location_text: 'RRB Mumbai, CST Area',
    lat: 18.9398, lon: 72.8354,
    posted_at: TODAY, last_date: LAST_DATE,
  },

  // ── Bengaluru ──────────────────────────────────────────────────────────────
  {
    title: 'Karnataka Administrative Services 2024',
    department: 'Karnataka Public Service Commission',
    source: 'KPSC',
    apply_url: 'https://kpsc.kar.nic.in',
    notification_pdf_url: null,
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    location_text: 'KPSC, Palace Road, Bengaluru',
    lat: 12.9716, lon: 77.5946,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'DRDO Scientist B Recruitment 2024',
    department: 'Defence Research and Development Organisation',
    source: 'DRDO',
    apply_url: 'https://rac.gov.in',
    notification_pdf_url: null,
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    location_text: 'DRDO Campus, Bengaluru',
    lat: 12.9952, lon: 77.5757,
    posted_at: TODAY, last_date: LAST_DATE,
  },

  // ── Chennai ────────────────────────────────────────────────────────────────
  {
    title: 'Tamil Nadu Civil Services Preliminary Exam 2024',
    department: 'Tamil Nadu Public Service Commission',
    source: 'TNPSC',
    apply_url: 'https://tnpsc.gov.in',
    notification_pdf_url: null,
    state: 'Tamil Nadu',
    district: 'Chennai',
    city: 'Chennai',
    location_text: 'TNPSC, Omanthoorar Estate, Chennai',
    lat: 13.0827, lon: 80.2707,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'RRB Chennai ALP Technician 2024',
    department: 'Railway Recruitment Board Chennai',
    source: 'RRB',
    apply_url: 'https://rrbchennai.gov.in',
    notification_pdf_url: null,
    state: 'Tamil Nadu',
    district: 'Chennai',
    city: 'Chennai',
    location_text: 'RRB Chennai, Park Town',
    lat: 13.0732, lon: 80.2595,
    posted_at: TODAY, last_date: LAST_DATE,
  },

  // ── Hyderabad ──────────────────────────────────────────────────────────────
  {
    title: 'TSPSC Group I Services 2024',
    department: 'Telangana State Public Service Commission',
    source: 'TSPSC',
    apply_url: 'https://tspsc.gov.in',
    notification_pdf_url: null,
    state: 'Telangana',
    district: 'Hyderabad',
    city: 'Hyderabad',
    location_text: 'TSPSC, Nampally, Hyderabad',
    lat: 17.3850, lon: 78.4867,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'ISRO Scientist/Engineer SC 2024',
    department: 'Indian Space Research Organisation',
    source: 'ISRO',
    apply_url: 'https://www.isro.gov.in/recruitment',
    notification_pdf_url: null,
    state: 'Telangana',
    district: 'Hyderabad',
    city: 'Hyderabad',
    location_text: 'ISRO SAC, Hyderabad',
    lat: 17.4400, lon: 78.3489,
    posted_at: TODAY, last_date: LAST_DATE,
  },

  // ── Kolkata ────────────────────────────────────────────────────────────────
  {
    title: 'West Bengal PSC WBCS 2024',
    department: 'West Bengal Public Service Commission',
    source: 'WBPSC',
    apply_url: 'https://pscwbapplication.in',
    notification_pdf_url: null,
    state: 'West Bengal',
    district: 'Kolkata',
    city: 'Kolkata',
    location_text: 'WBPSC, AJC Bose Road, Kolkata',
    lat: 22.5726, lon: 88.3639,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'RRB Kolkata NTPC Graduate Level 2024',
    department: 'Railway Recruitment Board Kolkata',
    source: 'RRB',
    apply_url: 'https://rrbkolkata.gov.in',
    notification_pdf_url: null,
    state: 'West Bengal',
    district: 'Kolkata',
    city: 'Kolkata',
    location_text: 'RRB Kolkata, Fairlie Place',
    lat: 22.5630, lon: 88.3498,
    posted_at: TODAY, last_date: LAST_DATE,
  },

  // ── Ahmedabad ──────────────────────────────────────────────────────────────
  {
    title: 'Gujarat PSC Class I & II Services 2024',
    department: 'Gujarat Public Service Commission',
    source: 'GPSC',
    apply_url: 'https://gpsc.gujarat.gov.in',
    notification_pdf_url: null,
    state: 'Gujarat',
    district: 'Ahmedabad',
    city: 'Ahmedabad',
    location_text: 'GPSC, Sector-10B, Gandhinagar',
    lat: 23.0225, lon: 72.5714,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'ONGC Assistant Technician Recruitment 2024',
    department: 'Oil and Natural Gas Corporation',
    source: 'ONGC',
    apply_url: 'https://ongcindia.com/careers',
    notification_pdf_url: null,
    state: 'Gujarat',
    district: 'Ahmedabad',
    city: 'Ahmedabad',
    location_text: 'ONGC Regional Office, Ahmedabad',
    lat: 23.0368, lon: 72.5600,
    posted_at: TODAY, last_date: LAST_DATE,
  },

  // ── Lucknow ────────────────────────────────────────────────────────────────
  {
    title: 'UPPSC PCS Prelims 2024',
    department: 'Uttar Pradesh Public Service Commission',
    source: 'UPPSC',
    apply_url: 'https://uppsc.up.nic.in',
    notification_pdf_url: null,
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    city: 'Lucknow',
    location_text: 'UPPSC, 10 Kasturba Gandhi Marg, Lucknow',
    lat: 26.8467, lon: 80.9462,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'UP Police Sub Inspector Recruitment 2024',
    department: 'UP Police Recruitment Board',
    source: 'UP Police',
    apply_url: 'https://uppbpb.gov.in',
    notification_pdf_url: null,
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    city: 'Lucknow',
    location_text: 'UPPRPB, Lucknow',
    lat: 26.8601, lon: 80.9300,
    posted_at: TODAY, last_date: LAST_DATE,
  },

  // ── Jaipur ─────────────────────────────────────────────────────────────────
  {
    title: 'Rajasthan PSC RAS 2024',
    department: 'Rajasthan Public Service Commission',
    source: 'RPSC',
    apply_url: 'https://rpsc.rajasthan.gov.in',
    notification_pdf_url: null,
    state: 'Rajasthan',
    district: 'Jaipur',
    city: 'Jaipur',
    location_text: 'RPSC, Ghooghara Ghati, Jaipur',
    lat: 26.9124, lon: 75.7873,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'Rajasthan High Court Clerk Grade II 2024',
    department: 'Rajasthan High Court',
    source: 'State PSC',
    apply_url: 'https://hcraj.nic.in',
    notification_pdf_url: null,
    state: 'Rajasthan',
    district: 'Jaipur',
    city: 'Jaipur',
    location_text: 'Rajasthan High Court, JLN Marg, Jaipur',
    lat: 26.9255, lon: 75.8213,
    posted_at: TODAY, last_date: LAST_DATE,
  },

  // ── Pune ───────────────────────────────────────────────────────────────────
  {
    title: 'MPSC Engineering Services 2024',
    department: 'Maharashtra Public Service Commission',
    source: 'MPSC',
    apply_url: 'https://mpsc.gov.in',
    notification_pdf_url: null,
    state: 'Maharashtra',
    district: 'Pune',
    city: 'Pune',
    location_text: 'MPSC Divisional Office, Shivajinagar, Pune',
    lat: 18.5204, lon: 73.8567,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'SEBI Grade A Officer Recruitment 2024',
    department: 'Securities and Exchange Board of India',
    source: 'SEBI',
    apply_url: 'https://www.sebi.gov.in/careers',
    notification_pdf_url: null,
    state: 'Maharashtra',
    district: 'Pune',
    city: 'Pune',
    location_text: 'SEBI Regional Office, Pune',
    lat: 18.5089, lon: 73.8798,
    posted_at: TODAY, last_date: LAST_DATE,
  },

  // ── Bhopal ─────────────────────────────────────────────────────────────────
  {
    title: 'MP PSC State Service Exam 2024',
    department: 'Madhya Pradesh Public Service Commission',
    source: 'MPPSC',
    apply_url: 'https://mppsc.mp.gov.in',
    notification_pdf_url: null,
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    city: 'Bhopal',
    location_text: 'MPPSC, Residency Area, Bhopal',
    lat: 23.2599, lon: 77.4126,
    posted_at: TODAY, last_date: LAST_DATE,
  },

  // ── Patna ──────────────────────────────────────────────────────────────────
  {
    title: 'BPSC 70th Combined Competitive Exam 2024',
    department: 'Bihar Public Service Commission',
    source: 'BPSC',
    apply_url: 'https://bpsc.bih.nic.in',
    notification_pdf_url: null,
    state: 'Bihar',
    district: 'Patna',
    city: 'Patna',
    location_text: 'BPSC, Jawaharlal Nehru Marg, Patna',
    lat: 25.5941, lon: 85.1376,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'Bihar Police SI Recruitment 2024',
    department: 'Bihar Police Services Commission',
    source: 'BPSSC',
    apply_url: 'https://bpssc.bih.nic.in',
    notification_pdf_url: null,
    state: 'Bihar',
    district: 'Patna',
    city: 'Patna',
    location_text: 'BPSSC Office, Patna',
    lat: 25.6093, lon: 85.1235,
    posted_at: TODAY, last_date: LAST_DATE,
  },

  // ── Chandigarh ─────────────────────────────────────────────────────────────
  {
    title: 'Punjab PSC Punjab Civil Services 2024',
    department: 'Punjab Public Service Commission',
    source: 'PPSC',
    apply_url: 'https://ppsc.gov.in',
    notification_pdf_url: null,
    state: 'Punjab',
    district: 'SAS Nagar',
    city: 'Chandigarh',
    location_text: 'PPSC, Sector 16, Chandigarh',
    lat: 30.7333, lon: 76.7794,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'Haryana PSC HCS 2024',
    department: 'Haryana Public Service Commission',
    source: 'HPSC',
    apply_url: 'https://hpsc.gov.in',
    notification_pdf_url: null,
    state: 'Haryana',
    district: 'Panchkula',
    city: 'Chandigarh',
    location_text: 'HPSC, Panchkula, Haryana',
    lat: 30.7007, lon: 76.8602,
    posted_at: TODAY, last_date: LAST_DATE,
  },

  // ── Thiruvananthapuram ─────────────────────────────────────────────────────
  {
    title: 'Kerala PSC Civil Services Exam 2024',
    department: 'Kerala Public Service Commission',
    source: 'KPSC',
    apply_url: 'https://keralapsc.gov.in',
    notification_pdf_url: null,
    state: 'Kerala',
    district: 'Thiruvananthapuram',
    city: 'Thiruvananthapuram',
    location_text: 'KPSC HQ, Pattom, Thiruvananthapuram',
    lat: 8.5241, lon: 76.9366,
    posted_at: TODAY, last_date: LAST_DATE,
  },

  // ── Bhubaneswar ────────────────────────────────────────────────────────────
  {
    title: 'Odisha PSC OCS Prelims 2024',
    department: 'Odisha Public Service Commission',
    source: 'OPSC',
    apply_url: 'https://opsc.gov.in',
    notification_pdf_url: null,
    state: 'Odisha',
    district: 'Khurda',
    city: 'Bhubaneswar',
    location_text: 'OPSC, 19 Dr PK Parija Road, Bhubaneswar',
    lat: 20.2961, lon: 85.8245,
    posted_at: TODAY, last_date: LAST_DATE,
  },

  // ── Guwahati ───────────────────────────────────────────────────────────────
  {
    title: 'Assam PSC Combined Competitive Exam 2024',
    department: 'Assam Public Service Commission',
    source: 'APSC',
    apply_url: 'https://apsc.nic.in',
    notification_pdf_url: null,
    state: 'Assam',
    district: 'Kamrup Metro',
    city: 'Guwahati',
    location_text: 'APSC, Jawaharnagar, Guwahati',
    lat: 26.1445, lon: 91.7362,
    posted_at: TODAY, last_date: LAST_DATE,
  },

  // ── Ranchi ─────────────────────────────────────────────────────────────────
  {
    title: 'JPSC Combined Civil Services 2024',
    department: 'Jharkhand Public Service Commission',
    source: 'JPSC',
    apply_url: 'https://jpsc.gov.in',
    notification_pdf_url: null,
    state: 'Jharkhand',
    district: 'Ranchi',
    city: 'Ranchi',
    location_text: 'JPSC, Circular Road, Ranchi',
    lat: 23.3441, lon: 85.3096,
    posted_at: TODAY, last_date: LAST_DATE,
  },

  // ── Raipur ─────────────────────────────────────────────────────────────────
  {
    title: 'CGPSC State Services Exam 2024',
    department: 'Chhattisgarh Public Service Commission',
    source: 'CGPSC',
    apply_url: 'https://psc.cg.gov.in',
    notification_pdf_url: null,
    state: 'Chhattisgarh',
    district: 'Raipur',
    city: 'Raipur',
    location_text: 'CGPSC, Shankar Nagar, Raipur',
    lat: 21.2514, lon: 81.6296,
    posted_at: TODAY, last_date: LAST_DATE,
  },

  // ── Dehradun ───────────────────────────────────────────────────────────────
  {
    title: 'Uttarakhand PSC Combined State Services 2024',
    department: 'Uttarakhand Public Service Commission',
    source: 'UKPSC',
    apply_url: 'https://psc.uk.gov.in',
    notification_pdf_url: null,
    state: 'Uttarakhand',
    district: 'Dehradun',
    city: 'Dehradun',
    location_text: 'UKPSC, Haridwar Road, Dehradun',
    lat: 30.3165, lon: 78.0322,
    posted_at: TODAY, last_date: LAST_DATE,
  },

  // ── Shimla ─────────────────────────────────────────────────────────────────
  {
    title: 'HPPSC Allied Services Exam 2024',
    department: 'Himachal Pradesh Public Service Commission',
    source: 'HPPSC',
    apply_url: 'https://hppsc.hp.gov.in',
    notification_pdf_url: null,
    state: 'Himachal Pradesh',
    district: 'Shimla',
    city: 'Shimla',
    location_text: 'HPPSC, Nigam Vihar, Shimla',
    lat: 31.1048, lon: 77.1734,
    posted_at: TODAY, last_date: LAST_DATE,
  },

  // ── Agartala ───────────────────────────────────────────────────────────────
  {
    title: 'TPSC Combined Competitive Services Exam 2024',
    department: 'Tripura Public Service Commission',
    source: 'TPSC',
    apply_url: 'https://tpsc.tripura.gov.in',
    notification_pdf_url: null,
    state: 'Tripura',
    district: 'West Tripura',
    city: 'Agartala',
    location_text: 'TPSC, Motor Stand Road, Agartala',
    lat: 23.8315, lon: 91.2868,
    posted_at: TODAY, last_date: LAST_DATE,
  },

  // ── National / Central positions in multiple cities ─────────────────────────
  {
    title: 'SBI Clerk Junior Associates Recruitment 2024',
    department: 'State Bank of India',
    source: 'Bank',
    apply_url: 'https://sbi.co.in/careers',
    notification_pdf_url: null,
    state: 'Maharashtra',
    district: 'Mumbai',
    city: 'Mumbai',
    location_text: 'SBI Corporate Centre, BKC, Mumbai',
    lat: 19.0596, lon: 72.8656,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'IBPS PO Common Recruitment Process 2024',
    department: 'Institute of Banking Personnel Selection',
    source: 'IBPS',
    apply_url: 'https://ibps.in',
    notification_pdf_url: null,
    state: 'Maharashtra',
    district: 'Mumbai',
    city: 'Mumbai',
    location_text: 'IBPS, Bandra-Kurla Complex, Mumbai',
    lat: 19.0553, lon: 72.8685,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'NHM Community Health Officer UP 2024',
    department: 'National Health Mission Uttar Pradesh',
    source: 'NHM',
    apply_url: 'https://nhm.gov.in',
    notification_pdf_url: null,
    state: 'Uttar Pradesh',
    district: 'Agra',
    city: 'Agra',
    location_text: 'NHM Divisional Office, Agra',
    lat: 27.1767, lon: 78.0081,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'Indian Army Agniveer Recruitment 2024',
    department: 'Indian Army',
    source: 'Defence',
    apply_url: 'https://joinindianarmy.nic.in',
    notification_pdf_url: null,
    state: 'Uttar Pradesh',
    district: 'Varanasi',
    city: 'Varanasi',
    location_text: 'Army Recruitment Office, Varanasi',
    lat: 25.3176, lon: 82.9739,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'NHM Staff Nurse Rajasthan 2024',
    department: 'National Health Mission Rajasthan',
    source: 'NHM',
    apply_url: 'https://nhm.rajasthan.gov.in',
    notification_pdf_url: null,
    state: 'Rajasthan',
    district: 'Jodhpur',
    city: 'Jodhpur',
    location_text: 'NHM Office, Residency Road, Jodhpur',
    lat: 26.2389, lon: 73.0243,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'Income Tax Inspector SSC CGL 2024',
    department: 'Income Tax Department',
    source: 'SSC',
    apply_url: 'https://ssc.nic.in',
    notification_pdf_url: null,
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    city: 'Coimbatore',
    location_text: 'Income Tax Office, Race Course Road, Coimbatore',
    lat: 11.0168, lon: 76.9558,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'Andhra Pradesh PSC Group I Services 2024',
    department: 'Andhra Pradesh Public Service Commission',
    source: 'APPSC',
    apply_url: 'https://psc.ap.gov.in',
    notification_pdf_url: null,
    state: 'Andhra Pradesh',
    district: 'Guntur',
    city: 'Amaravati',
    location_text: 'APPSC, Velagapudi, Amaravati',
    lat: 16.5131, lon: 80.5157,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'GAIL Non-Executive Recruitment 2024',
    department: 'Gas Authority of India Limited',
    source: 'PSU',
    apply_url: 'https://gailonline.com/careers',
    notification_pdf_url: null,
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    location_text: 'GAIL Bhavan, Nelson Mandela Road, New Delhi',
    lat: 28.5665, lon: 77.1857,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'Central Bank of India Clerk Recruitment 2024',
    department: 'Central Bank of India',
    source: 'Bank',
    apply_url: 'https://centralbankofindia.co.in/careers',
    notification_pdf_url: null,
    state: 'Maharashtra',
    district: 'Mumbai',
    city: 'Mumbai',
    location_text: 'Central Bank of India, Fort, Mumbai',
    lat: 18.9345, lon: 72.8355,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'Canara Bank PO Recruitment 2024',
    department: 'Canara Bank',
    source: 'Bank',
    apply_url: 'https://canarabank.com/careers',
    notification_pdf_url: null,
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    location_text: 'Canara Bank HO, JC Road, Bengaluru',
    lat: 12.9632, lon: 77.5775,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'Surat Municipal Corporation Recruitment 2024',
    department: 'Surat Municipal Corporation',
    source: 'Municipality',
    apply_url: 'https://suratmunicipal.gov.in',
    notification_pdf_url: null,
    state: 'Gujarat',
    district: 'Surat',
    city: 'Surat',
    location_text: 'SMC Mukhya Karyalay, Muglisara, Surat',
    lat: 21.1702, lon: 72.8311,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'Nagpur ZP Health Department Recruitment 2024',
    department: 'Zila Parishad Nagpur',
    source: 'State PSC',
    apply_url: 'https://nagpurzp.com',
    notification_pdf_url: null,
    state: 'Maharashtra',
    district: 'Nagpur',
    city: 'Nagpur',
    location_text: 'ZP Office, Civil Lines, Nagpur',
    lat: 21.1458, lon: 79.0882,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'Indore Municipal Corporation Recruitment 2024',
    department: 'Indore Municipal Corporation',
    source: 'Municipality',
    apply_url: 'https://imc.gov.in',
    notification_pdf_url: null,
    state: 'Madhya Pradesh',
    district: 'Indore',
    city: 'Indore',
    location_text: 'IMC, MG Road, Indore',
    lat: 22.7196, lon: 75.8577,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'Vizag Steel Plant Management Trainee 2024',
    department: 'Rashtriya Ispat Nigam Ltd',
    source: 'PSU',
    apply_url: 'https://vizagsteel.com/careers',
    notification_pdf_url: null,
    state: 'Andhra Pradesh',
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    location_text: 'RINL, Visakhapatnam Steel Plant',
    lat: 17.6868, lon: 83.2185,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'HAL Apprentice Recruitment 2024',
    department: 'Hindustan Aeronautics Limited',
    source: 'PSU',
    apply_url: 'https://hal-india.co.in/careers',
    notification_pdf_url: null,
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    location_text: 'HAL Heritage Centre, HAL Airport Road, Bengaluru',
    lat: 12.9519, lon: 77.6666,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'BEL Probationary Engineer 2024',
    department: 'Bharat Electronics Limited',
    source: 'PSU',
    apply_url: 'https://bel-india.in/careers',
    notification_pdf_url: null,
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    location_text: 'BEL HQ, Outer Ring Road, Bengaluru',
    lat: 13.0012, lon: 77.5762,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'NTPC Executive Trainee Recruitment 2024',
    department: 'National Thermal Power Corporation',
    source: 'PSU',
    apply_url: 'https://ntpc.co.in/careers',
    notification_pdf_url: null,
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    location_text: 'NTPC Bhavan, Scope Complex, New Delhi',
    lat: 28.6235, lon: 77.2160,
    posted_at: TODAY, last_date: LAST_DATE,
  },
  {
    title: 'Coal India Management Trainee 2024',
    department: 'Coal India Limited',
    source: 'PSU',
    apply_url: 'https://coalindia.in/careers',
    notification_pdf_url: null,
    state: 'West Bengal',
    district: 'Kolkata',
    city: 'Kolkata',
    location_text: 'Coal Bhavan, Premises 04 MAR, Kolkata',
    lat: 22.5456, lon: 88.3419,
    posted_at: TODAY, last_date: LAST_DATE,
  },
];

module.exports = SAMPLE_JOBS;
