/**
 * Seed script – inserts 40 sample jobs across India into the jobs table.
 *
 * Usage:
 *   cd backend && node scripts/seed-jobs.js
 *   Or via npm:  npm run seed  (from backend/)
 *
 * Requires DATABASE_URL in the environment (or a .env file one level up).
 */

'use strict';

require('dotenv').config({ path: '../.env' });

const { Pool } = require('pg');

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false,
});

// 40 sample jobs spanning all major Indian states
const JOBS = [
  {
    title: 'Junior Engineer (Civil)',
    organization: 'Public Works Department',
    board: 'UPPSC',
    category: 'Engineering',
    status: 'active',
    apply_url: 'https://uppsc.up.nic.in',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    city: 'Lucknow',
    location_text: 'Lucknow, Uttar Pradesh',
    lat: 26.8467, lon: 80.9462,
    posted_at: '2024-03-01', last_date: '2024-04-15',
  },
  {
    title: 'Staff Nurse (Grade II)',
    organization: 'All India Institute of Medical Sciences',
    board: 'AIIMS',
    category: 'Medical',
    status: 'active',
    apply_url: 'https://aiims.edu',
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    location_text: 'AIIMS, New Delhi',
    lat: 28.5672, lon: 77.2100,
    posted_at: '2024-03-05', last_date: '2024-04-20',
  },
  {
    title: 'Sub-Inspector (Police)',
    organization: 'Maharashtra Police',
    board: 'MPSC',
    category: 'Police',
    status: 'active',
    apply_url: 'https://mpsc.gov.in',
    state: 'Maharashtra',
    district: 'Mumbai',
    city: 'Mumbai',
    location_text: 'Mumbai, Maharashtra',
    lat: 19.0760, lon: 72.8777,
    posted_at: '2024-02-20', last_date: '2024-03-31',
  },
  {
    title: 'Clerk (Ministerial)',
    organization: 'Tamil Nadu Public Service Commission',
    board: 'TNPSC',
    category: 'Clerical',
    status: 'active',
    apply_url: 'https://tnpsc.gov.in',
    state: 'Tamil Nadu',
    district: 'Chennai',
    city: 'Chennai',
    location_text: 'Chennai, Tamil Nadu',
    lat: 13.0827, lon: 80.2707,
    posted_at: '2024-03-10', last_date: '2024-04-30',
  },
  {
    title: 'Constable (GD)',
    organization: 'Central Reserve Police Force',
    board: 'SSC',
    category: 'Defence',
    status: 'active',
    apply_url: 'https://ssc.nic.in',
    state: 'All India',
    district: 'Pan India',
    city: 'Pan India',
    location_text: 'All India',
    lat: 20.5937, lon: 78.9629,
    posted_at: '2024-02-15', last_date: '2024-03-28',
  },
  {
    title: 'Assistant Professor (Computer Science)',
    organization: 'Gujarat University',
    board: 'GPSC',
    category: 'Education',
    status: 'active',
    apply_url: 'https://gpsc.gujarat.gov.in',
    state: 'Gujarat',
    district: 'Ahmedabad',
    city: 'Ahmedabad',
    location_text: 'Ahmedabad, Gujarat',
    lat: 23.0225, lon: 72.5714,
    posted_at: '2024-03-12', last_date: '2024-04-25',
  },
  {
    title: 'Probationary Officer',
    organization: 'State Bank of India',
    board: 'SBI',
    category: 'Banking',
    status: 'active',
    apply_url: 'https://sbi.co.in/careers',
    state: 'All India',
    district: 'Pan India',
    city: 'Pan India',
    location_text: 'All India',
    lat: 20.5937, lon: 78.9629,
    posted_at: '2024-03-15', last_date: '2024-04-10',
  },
  {
    title: 'Loco Pilot (Assistant)',
    organization: 'Indian Railways',
    board: 'RRB',
    category: 'Railways',
    status: 'active',
    apply_url: 'https://indianrailways.gov.in',
    state: 'Karnataka',
    district: 'Bangalore',
    city: 'Bengaluru',
    location_text: 'Bengaluru, Karnataka',
    lat: 12.9716, lon: 77.5946,
    posted_at: '2024-02-28', last_date: '2024-04-05',
  },
  {
    title: 'Tax Assistant',
    organization: 'Income Tax Department',
    board: 'SSC',
    category: 'Finance',
    status: 'active',
    apply_url: 'https://ssc.nic.in',
    state: 'Rajasthan',
    district: 'Jaipur',
    city: 'Jaipur',
    location_text: 'Jaipur, Rajasthan',
    lat: 26.9124, lon: 75.7873,
    posted_at: '2024-03-08', last_date: '2024-04-18',
  },
  {
    title: 'Junior Research Fellow (Chemistry)',
    organization: 'CSIR',
    board: 'CSIR-UGC NET',
    category: 'Research',
    status: 'active',
    apply_url: 'https://csirhrdg.res.in',
    state: 'West Bengal',
    district: 'Kolkata',
    city: 'Kolkata',
    location_text: 'Kolkata, West Bengal',
    lat: 22.5726, lon: 88.3639,
    posted_at: '2024-03-18', last_date: '2024-05-01',
  },
  {
    title: 'Forest Guard',
    organization: 'Madhya Pradesh Forest Department',
    board: 'MPPEB',
    category: 'Forest',
    status: 'active',
    apply_url: 'https://peb.mp.gov.in',
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    city: 'Bhopal',
    location_text: 'Bhopal, Madhya Pradesh',
    lat: 23.2599, lon: 77.4126,
    posted_at: '2024-02-25', last_date: '2024-03-30',
  },
  {
    title: 'Stenographer Grade C',
    organization: 'High Court of Punjab & Haryana',
    board: 'Punjab & Haryana HC',
    category: 'Judicial',
    status: 'active',
    apply_url: 'https://highcourtchd.gov.in',
    state: 'Punjab',
    district: 'Chandigarh',
    city: 'Chandigarh',
    location_text: 'Chandigarh, Punjab',
    lat: 30.7333, lon: 76.7794,
    posted_at: '2024-03-20', last_date: '2024-04-22',
  },
  {
    title: 'Veterinary Officer',
    organization: 'Bihar Animal Husbandry Department',
    board: 'BPSC',
    category: 'Veterinary',
    status: 'active',
    apply_url: 'https://bpsc.bih.nic.in',
    state: 'Bihar',
    district: 'Patna',
    city: 'Patna',
    location_text: 'Patna, Bihar',
    lat: 25.5941, lon: 85.1376,
    posted_at: '2024-03-22', last_date: '2024-04-28',
  },
  {
    title: 'Executive Engineer (Electrical)',
    organization: 'Odisha Power Transmission Corporation',
    board: 'OPSC',
    category: 'Engineering',
    status: 'active',
    apply_url: 'https://opsc.gov.in',
    state: 'Odisha',
    district: 'Bhubaneswar',
    city: 'Bhubaneswar',
    location_text: 'Bhubaneswar, Odisha',
    lat: 20.2961, lon: 85.8245,
    posted_at: '2024-03-14', last_date: '2024-04-20',
  },
  {
    title: 'Panchayat Secretary',
    organization: 'Kerala PSC',
    board: 'KPSC',
    category: 'Administrative',
    status: 'active',
    apply_url: 'https://keralapsc.gov.in',
    state: 'Kerala',
    district: 'Thiruvananthapuram',
    city: 'Thiruvananthapuram',
    location_text: 'Thiruvananthapuram, Kerala',
    lat: 8.5241, lon: 76.9366,
    posted_at: '2024-03-16', last_date: '2024-04-30',
  },
  {
    title: 'Postal Assistant',
    organization: 'India Post',
    board: 'India Post',
    category: 'Postal',
    status: 'active',
    apply_url: 'https://indiapostgdsonline.gov.in',
    state: 'Telangana',
    district: 'Hyderabad',
    city: 'Hyderabad',
    location_text: 'Hyderabad, Telangana',
    lat: 17.3850, lon: 78.4867,
    posted_at: '2024-02-18', last_date: '2024-03-25',
  },
  {
    title: 'Group D Technician',
    organization: 'Indian Army EME Corps',
    board: 'Indian Army',
    category: 'Defence',
    status: 'active',
    apply_url: 'https://joinindianarmy.nic.in',
    state: 'Uttarakhand',
    district: 'Dehradun',
    city: 'Dehradun',
    location_text: 'Dehradun, Uttarakhand',
    lat: 30.3165, lon: 78.0322,
    posted_at: '2024-03-25', last_date: '2024-04-28',
  },
  {
    title: 'Assistant Commandant (BSF)',
    organization: 'Border Security Force',
    board: 'UPSC',
    category: 'Defence',
    status: 'active',
    apply_url: 'https://upsc.gov.in',
    state: 'All India',
    district: 'Pan India',
    city: 'Pan India',
    location_text: 'All India',
    lat: 20.5937, lon: 78.9629,
    posted_at: '2024-03-28', last_date: '2024-05-10',
  },
  {
    title: 'District Level Officer (DRDA)',
    organization: 'Andhra Pradesh Government',
    board: 'APPSC',
    category: 'Administrative',
    status: 'active',
    apply_url: 'https://psc.ap.gov.in',
    state: 'Andhra Pradesh',
    district: 'Vijayawada',
    city: 'Vijayawada',
    location_text: 'Vijayawada, Andhra Pradesh',
    lat: 16.5062, lon: 80.6480,
    posted_at: '2024-03-19', last_date: '2024-04-25',
  },
  {
    title: 'Electrical Inspector',
    organization: 'Jharkhand Electricity Regulatory Commission',
    board: 'JPSC',
    category: 'Engineering',
    status: 'active',
    apply_url: 'https://jpsc.gov.in',
    state: 'Jharkhand',
    district: 'Ranchi',
    city: 'Ranchi',
    location_text: 'Ranchi, Jharkhand',
    lat: 23.3441, lon: 85.3096,
    posted_at: '2024-02-22', last_date: '2024-04-02',
  },
  {
    title: 'Senior Auditor',
    organization: 'Comptroller and Auditor General of India',
    board: 'SSC',
    category: 'Finance',
    status: 'active',
    apply_url: 'https://ssc.nic.in',
    state: 'Chhattisgarh',
    district: 'Raipur',
    city: 'Raipur',
    location_text: 'Raipur, Chhattisgarh',
    lat: 21.2514, lon: 81.6296,
    posted_at: '2024-03-11', last_date: '2024-04-19',
  },
  {
    title: 'Block Development Officer',
    organization: 'Assam Government',
    board: 'APSC',
    category: 'Administrative',
    status: 'active',
    apply_url: 'https://apsc.nic.in',
    state: 'Assam',
    district: 'Guwahati',
    city: 'Guwahati',
    location_text: 'Guwahati, Assam',
    lat: 26.1445, lon: 91.7362,
    posted_at: '2024-03-05', last_date: '2024-04-15',
  },
  {
    title: 'Junior Translator (Hindi)',
    organization: 'Ministry of External Affairs',
    board: 'SSC',
    category: 'Language',
    status: 'active',
    apply_url: 'https://ssc.nic.in',
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    location_text: 'New Delhi, Delhi',
    lat: 28.6139, lon: 77.2090,
    posted_at: '2024-03-23', last_date: '2024-04-27',
  },
  {
    title: 'Agriculture Officer',
    organization: 'Punjab Agriculture Department',
    board: 'PPSC',
    category: 'Agriculture',
    status: 'active',
    apply_url: 'https://ppsc.gov.in',
    state: 'Punjab',
    district: 'Ludhiana',
    city: 'Ludhiana',
    location_text: 'Ludhiana, Punjab',
    lat: 30.9010, lon: 75.8573,
    posted_at: '2024-02-27', last_date: '2024-04-06',
  },
  {
    title: 'Pharmacist Grade II',
    organization: 'Haryana Health Department',
    board: 'HSSC',
    category: 'Medical',
    status: 'active',
    apply_url: 'https://hssc.gov.in',
    state: 'Haryana',
    district: 'Gurugram',
    city: 'Gurugram',
    location_text: 'Gurugram, Haryana',
    lat: 28.4595, lon: 77.0266,
    posted_at: '2024-03-06', last_date: '2024-04-12',
  },
  {
    title: 'Fire Station Officer',
    organization: 'Himachal Pradesh Fire & Emergency Services',
    board: 'HPPSC',
    category: 'Emergency Services',
    status: 'active',
    apply_url: 'https://hppsc.hp.gov.in',
    state: 'Himachal Pradesh',
    district: 'Shimla',
    city: 'Shimla',
    location_text: 'Shimla, Himachal Pradesh',
    lat: 31.1048, lon: 77.1734,
    posted_at: '2024-03-17', last_date: '2024-04-23',
  },
  {
    title: 'Judicial Magistrate',
    organization: 'High Court of Gauhati',
    board: 'Gauhati HC',
    category: 'Judicial',
    status: 'active',
    apply_url: 'https://ghconline.gov.in',
    state: 'Meghalaya',
    district: 'Shillong',
    city: 'Shillong',
    location_text: 'Shillong, Meghalaya',
    lat: 25.5788, lon: 91.8933,
    posted_at: '2024-03-09', last_date: '2024-04-16',
  },
  {
    title: 'Sports Coach (Kabaddi)',
    organization: 'Sports Authority of India',
    board: 'SAI',
    category: 'Sports',
    status: 'active',
    apply_url: 'https://sportsauthorityofindia.nic.in',
    state: 'Haryana',
    district: 'Panchkula',
    city: 'Panchkula',
    location_text: 'Panchkula, Haryana',
    lat: 30.6942, lon: 76.8606,
    posted_at: '2024-03-21', last_date: '2024-04-26',
  },
  {
    title: 'Inspector of Taxes',
    organization: 'Rajasthan Commercial Taxes Department',
    board: 'RPSC',
    category: 'Finance',
    status: 'active',
    apply_url: 'https://rpsc.rajasthan.gov.in',
    state: 'Rajasthan',
    district: 'Jodhpur',
    city: 'Jodhpur',
    location_text: 'Jodhpur, Rajasthan',
    lat: 26.2389, lon: 73.0243,
    posted_at: '2024-03-26', last_date: '2024-05-03',
  },
  {
    title: 'Programmer (IT)',
    organization: 'National Informatics Centre',
    board: 'NIC',
    category: 'IT',
    status: 'active',
    apply_url: 'https://nicsi.com',
    state: 'Karnataka',
    district: 'Mysuru',
    city: 'Mysuru',
    location_text: 'Mysuru, Karnataka',
    lat: 12.2958, lon: 76.6394,
    posted_at: '2024-03-02', last_date: '2024-04-09',
  },
  {
    title: 'Mine Inspector',
    organization: 'Directorate General of Mines Safety',
    board: 'UPSC',
    category: 'Engineering',
    status: 'active',
    apply_url: 'https://upsc.gov.in',
    state: 'Jharkhand',
    district: 'Dhanbad',
    city: 'Dhanbad',
    location_text: 'Dhanbad, Jharkhand',
    lat: 23.7957, lon: 86.4304,
    posted_at: '2024-03-04', last_date: '2024-04-11',
  },
  {
    title: 'Anganwadi Supervisor',
    organization: 'Women & Child Development Department',
    board: 'MHPSC',
    category: 'Social Welfare',
    status: 'active',
    apply_url: 'https://mahapariksha.gov.in',
    state: 'Maharashtra',
    district: 'Pune',
    city: 'Pune',
    location_text: 'Pune, Maharashtra',
    lat: 18.5204, lon: 73.8567,
    posted_at: '2024-02-29', last_date: '2024-04-07',
  },
  {
    title: 'Library & Information Officer',
    organization: 'Central University of Rajasthan',
    board: 'Central University',
    category: 'Education',
    status: 'active',
    apply_url: 'https://curaj.ac.in',
    state: 'Rajasthan',
    district: 'Ajmer',
    city: 'Ajmer',
    location_text: 'Ajmer, Rajasthan',
    lat: 26.4499, lon: 74.6399,
    posted_at: '2024-03-13', last_date: '2024-04-22',
  },
  {
    title: 'Fisheries Development Officer',
    organization: 'Andaman & Nicobar Islands Administration',
    board: 'A&N Admin',
    category: 'Agriculture',
    status: 'active',
    apply_url: 'https://andaman.gov.in',
    state: 'Andaman & Nicobar Islands',
    district: 'South Andaman',
    city: 'Port Blair',
    location_text: 'Port Blair, Andaman & Nicobar Islands',
    lat: 11.6234, lon: 92.7265,
    posted_at: '2024-03-07', last_date: '2024-04-14',
  },
  {
    title: 'Nursing Officer',
    organization: 'AIIMS Jodhpur',
    board: 'AIIMS',
    category: 'Medical',
    status: 'active',
    apply_url: 'https://aiimsjodhpur.edu.in',
    state: 'Rajasthan',
    district: 'Jodhpur',
    city: 'Jodhpur',
    location_text: 'Jodhpur, Rajasthan',
    lat: 26.2521, lon: 73.0251,
    posted_at: '2024-03-29', last_date: '2024-05-08',
  },
  {
    title: 'Canal Patwari',
    organization: 'Irrigation Department Punjab',
    board: 'PSSSB',
    category: 'Administrative',
    status: 'active',
    apply_url: 'https://psssb.punjab.gov.in',
    state: 'Punjab',
    district: 'Amritsar',
    city: 'Amritsar',
    location_text: 'Amritsar, Punjab',
    lat: 31.6340, lon: 74.8723,
    posted_at: '2024-02-26', last_date: '2024-04-03',
  },
  {
    title: 'Cipher Operator',
    organization: 'Intelligence Bureau',
    board: 'IB',
    category: 'Defence',
    status: 'active',
    apply_url: 'https://mha.gov.in',
    state: 'All India',
    district: 'Pan India',
    city: 'Pan India',
    location_text: 'All India',
    lat: 20.5937, lon: 78.9629,
    posted_at: '2024-03-27', last_date: '2024-04-29',
  },
  {
    title: 'Assistant Director (Town Planning)',
    organization: 'Greater Hyderabad Municipal Corporation',
    board: 'TSPSC',
    category: 'Engineering',
    status: 'active',
    apply_url: 'https://tspsc.gov.in',
    state: 'Telangana',
    district: 'Hyderabad',
    city: 'Hyderabad',
    location_text: 'Hyderabad, Telangana',
    lat: 17.4065, lon: 78.4772,
    posted_at: '2024-03-03', last_date: '2024-04-13',
  },
  {
    title: 'Statistical Investigator Grade II',
    organization: 'Ministry of Statistics',
    board: 'SSC',
    category: 'Research',
    status: 'active',
    apply_url: 'https://ssc.nic.in',
    state: 'All India',
    district: 'Pan India',
    city: 'Pan India',
    location_text: 'All India',
    lat: 20.5937, lon: 78.9629,
    posted_at: '2024-03-24', last_date: '2024-04-29',
  },
  {
    title: 'Deputy Superintendent of Police',
    organization: 'Goa Police',
    board: 'GPSC Goa',
    category: 'Police',
    status: 'active',
    apply_url: 'https://gpsc.goa.gov.in',
    state: 'Goa',
    district: 'North Goa',
    city: 'Panaji',
    location_text: 'Panaji, Goa',
    lat: 15.4989, lon: 73.8278,
    posted_at: '2024-03-30', last_date: '2024-05-06',
  },
];

async function seed() {
  console.log(`Seeding ${JOBS.length} jobs…`);
  let inserted = 0;

  for (const job of JOBS) {
    try {
      await pool.query(
        `INSERT INTO jobs
           (title, organization, board, category, status, apply_url,
            state, district, city, location_text, lat, lon, posted_at, last_date)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
         ON CONFLICT DO NOTHING`,
        [
          job.title, job.organization, job.board, job.category,
          job.status, job.apply_url,
          job.state, job.district, job.city, job.location_text,
          job.lat, job.lon,
          job.posted_at, job.last_date,
        ]
      );
      inserted++;
    } catch (err) {
      console.error(`Failed to insert "${job.title}":`, err.message);
    }
  }

  console.log(`✓ Inserted ${inserted} / ${JOBS.length} jobs.`);
}

seed()
  .then(() => pool.end())
  .catch((err) => {
    console.error('Seed error:', err);
    pool.end();
    process.exit(1);
  });
