'use strict';

/**
 * Seed script – inserts ~50 sample government jobs across India.
 * Run: node backend/db/seed.js  (from repo root, with .env present)
 *   or: npm run seed  (from backend/)
 */

require('dotenv').config({ path: require('path').resolve(__dirname, '../../.env') });

const { createClient } = require('@supabase/supabase-js');

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

/* eslint-disable */
const JOBS = [
  // ── Delhi / NCR cluster ────────────────────────────────────────────────
  {
    title: 'Junior Assistant (SSC CHSL)',
    organization: 'Staff Selection Commission',
    category: 'Central Govt',
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    lat: 28.6139,
    lon: 77.209,
    last_date: '2025-03-31',
    status: 'active',
    vacancies: 4500,
    apply_url: 'https://ssc.nic.in',
    notification_url: 'https://ssc.nic.in/notices/ssc-chsl-2024.pdf',
  },
  {
    title: 'Multi Tasking Staff (SSC MTS)',
    organization: 'Staff Selection Commission',
    category: 'Central Govt',
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    lat: 28.6297,
    lon: 77.2194,
    last_date: '2025-04-15',
    status: 'active',
    vacancies: 8326,
    apply_url: 'https://ssc.nic.in',
    notification_url: 'https://ssc.nic.in/notices/ssc-mts-2024.pdf',
  },
  {
    title: 'Combined Graduate Level (SSC CGL)',
    organization: 'Staff Selection Commission',
    category: 'Central Govt',
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    lat: 28.6353,
    lon: 77.2249,
    last_date: '2025-05-01',
    status: 'active',
    vacancies: 17727,
    apply_url: 'https://ssc.nic.in',
    notification_url: 'https://ssc.nic.in/notices/ssc-cgl-2024.pdf',
  },
  {
    title: 'UPSC Civil Services (IAS/IPS/IFS)',
    organization: 'Union Public Service Commission',
    category: 'Central Govt',
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    lat: 28.6198,
    lon: 77.2037,
    last_date: '2025-02-20',
    status: 'active',
    vacancies: 1056,
    apply_url: 'https://upsc.gov.in',
    notification_url: 'https://upsc.gov.in/sites/default/files/Notif-CSP-2024.pdf',
  },
  {
    title: 'UPSC NDA & NA Examination',
    organization: 'Union Public Service Commission',
    category: 'Defence',
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    lat: 28.6219,
    lon: 77.2058,
    last_date: '2025-06-10',
    status: 'upcoming',
    vacancies: 400,
    apply_url: 'https://upsc.gov.in',
    notification_url: 'https://upsc.gov.in/sites/default/files/Notif-NDA-2024.pdf',
  },

  // ── Mumbai / Maharashtra cluster ────────────────────────────────────────
  {
    title: 'Clerk-cum-Typist (MPSC)',
    organization: 'Maharashtra Public Service Commission',
    category: 'State Govt',
    state: 'Maharashtra',
    district: 'Mumbai',
    city: 'Mumbai',
    lat: 19.076,
    lon: 72.8777,
    last_date: '2025-03-20',
    status: 'active',
    vacancies: 1200,
    apply_url: 'https://mpsc.gov.in',
    notification_url: 'https://mpsc.gov.in/downloads/advt-clerk-2024.pdf',
  },
  {
    title: 'Assistant Engineer (PWD Maharashtra)',
    organization: 'Maharashtra PWD',
    category: 'State Govt',
    state: 'Maharashtra',
    district: 'Mumbai',
    city: 'Mumbai',
    lat: 19.0821,
    lon: 72.8844,
    last_date: '2025-04-30',
    status: 'active',
    vacancies: 490,
    apply_url: 'https://mahaonline.gov.in',
    notification_url: 'https://mahaonline.gov.in/SitePages/Advertise.aspx',
  },
  {
    title: 'Police Constable (Maharashtra Police)',
    organization: 'Maharashtra State Police',
    category: 'State Govt',
    state: 'Maharashtra',
    district: 'Pune',
    city: 'Pune',
    lat: 18.5204,
    lon: 73.8567,
    last_date: '2025-03-15',
    status: 'active',
    vacancies: 10000,
    apply_url: 'https://mahapolice.gov.in',
    notification_url: 'https://mahapolice.gov.in/notifications/constable-2024',
  },
  {
    title: 'Group C Posts (BSNL Maharashtra)',
    organization: 'BSNL',
    category: 'PSU',
    state: 'Maharashtra',
    district: 'Nagpur',
    city: 'Nagpur',
    lat: 21.1458,
    lon: 79.0882,
    last_date: '2025-02-28',
    status: 'active',
    vacancies: 250,
    apply_url: 'https://bsnl.co.in',
    notification_url: 'https://bsnl.co.in/opencms/export/sites/default/en/notices/',
  },

  // ── Bengaluru / Karnataka cluster ───────────────────────────────────────
  {
    title: 'FDA/SDA (KPSC)',
    organization: 'Karnataka Public Service Commission',
    category: 'State Govt',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    lat: 12.9716,
    lon: 77.5946,
    last_date: '2025-04-01',
    status: 'active',
    vacancies: 4450,
    apply_url: 'https://kpsc.kar.nic.in',
    notification_url: 'https://kpsc.kar.nic.in/new_web/FdaSdaNotification2024.pdf',
  },
  {
    title: 'Group D Recruitment (South Western Railway)',
    organization: 'Indian Railways – SWR',
    category: 'Railway',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    lat: 12.9788,
    lon: 77.5996,
    last_date: '2025-05-15',
    status: 'upcoming',
    vacancies: 3000,
    apply_url: 'https://rrcswr.com',
    notification_url: 'https://rrcswr.com/assets/Level1-notification-2024.pdf',
  },
  {
    title: 'Technical Superintendent (HAL Bengaluru)',
    organization: 'Hindustan Aeronautics Limited',
    category: 'PSU',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    lat: 12.9441,
    lon: 77.5681,
    last_date: '2025-03-31',
    status: 'active',
    vacancies: 120,
    apply_url: 'https://hal-india.co.in',
    notification_url: 'https://hal-india.co.in/careers/Apprentice-notification.pdf',
  },

  // ── Chennai / Tamil Nadu cluster ────────────────────────────────────────
  {
    title: 'Group I Services (TNPSC)',
    organization: 'Tamil Nadu Public Service Commission',
    category: 'State Govt',
    state: 'Tamil Nadu',
    district: 'Chennai',
    city: 'Chennai',
    lat: 13.0827,
    lon: 80.2707,
    last_date: '2025-04-20',
    status: 'active',
    vacancies: 200,
    apply_url: 'https://tnpsc.gov.in',
    notification_url: 'https://tnpsc.gov.in/english/GroupI_2024_Notification.pdf',
  },
  {
    title: 'Constable (Tamil Nadu Police)',
    organization: 'Tamil Nadu Police',
    category: 'State Govt',
    state: 'Tamil Nadu',
    district: 'Chennai',
    city: 'Chennai',
    lat: 13.0694,
    lon: 80.2781,
    last_date: '2025-05-31',
    status: 'upcoming',
    vacancies: 7000,
    apply_url: 'https://tnusrbonline.org',
    notification_url: 'https://tnusrbonline.org/constable-2024-notification',
  },
  {
    title: 'Junior Engineer Civil (TNPWD)',
    organization: 'Tamil Nadu Public Works Department',
    category: 'State Govt',
    state: 'Tamil Nadu',
    district: 'Chennai',
    city: 'Chennai',
    lat: 13.0978,
    lon: 80.2775,
    last_date: '2025-03-10',
    status: 'closed',
    vacancies: 330,
    apply_url: 'https://tnpsc.gov.in',
    notification_url: 'https://tnpsc.gov.in/english/JE_2024_Notification.pdf',
  },

  // ── Hyderabad / Telangana cluster ───────────────────────────────────────
  {
    title: 'Group I Services (TSPSC)',
    organization: 'Telangana State PSC',
    category: 'State Govt',
    state: 'Telangana',
    district: 'Hyderabad',
    city: 'Hyderabad',
    lat: 17.385,
    lon: 78.4867,
    last_date: '2025-04-10',
    status: 'active',
    vacancies: 563,
    apply_url: 'https://tspsc.gov.in',
    notification_url: 'https://tspsc.gov.in/Notifications/Group1_2024.pdf',
  },
  {
    title: 'Junior Lineman (TSSPDCL)',
    organization: 'Telangana Southern Power Distribution Company',
    category: 'PSU',
    state: 'Telangana',
    district: 'Hyderabad',
    city: 'Hyderabad',
    lat: 17.3759,
    lon: 78.4921,
    last_date: '2025-03-25',
    status: 'active',
    vacancies: 1785,
    apply_url: 'https://tsspdcl.cgg.gov.in',
    notification_url: 'https://tsspdcl.cgg.gov.in/jlm2024.pdf',
  },

  // ── Kolkata / West Bengal cluster ───────────────────────────────────────
  {
    title: 'Clerkship Examination (WBPSC)',
    organization: 'West Bengal Public Service Commission',
    category: 'State Govt',
    state: 'West Bengal',
    district: 'Kolkata',
    city: 'Kolkata',
    lat: 22.5726,
    lon: 88.3639,
    last_date: '2025-03-05',
    status: 'active',
    vacancies: 6000,
    apply_url: 'https://wbpsc.gov.in',
    notification_url: 'https://wbpsc.gov.in/Download?fileName=Clerk_Notification_2024.pdf',
  },
  {
    title: 'Sub Inspector of Police (WBPRB)',
    organization: 'West Bengal Police Recruitment Board',
    category: 'State Govt',
    state: 'West Bengal',
    district: 'Kolkata',
    city: 'Kolkata',
    lat: 22.5815,
    lon: 88.3502,
    last_date: '2025-05-20',
    status: 'upcoming',
    vacancies: 1200,
    apply_url: 'https://wbprb.applythrunet.co.in',
    notification_url: 'https://wbprb.applythrunet.co.in/si_notification_2024.pdf',
  },

  // ── Ahmedabad / Gujarat ─────────────────────────────────────────────────
  {
    title: 'Class III Posts (GPSC)',
    organization: 'Gujarat Public Service Commission',
    category: 'State Govt',
    state: 'Gujarat',
    district: 'Ahmedabad',
    city: 'Ahmedabad',
    lat: 23.0225,
    lon: 72.5714,
    last_date: '2025-04-05',
    status: 'active',
    vacancies: 2400,
    apply_url: 'https://gpsc.gujarat.gov.in',
    notification_url: 'https://gpsc.gujarat.gov.in/notification/class3-2024.pdf',
  },
  {
    title: 'Staff Nurse (GMERS)',
    organization: 'Gujarat Medical Education & Research Society',
    category: 'State Govt',
    state: 'Gujarat',
    district: 'Gandhinagar',
    city: 'Gandhinagar',
    lat: 23.2156,
    lon: 72.6369,
    last_date: '2025-03-18',
    status: 'active',
    vacancies: 500,
    apply_url: 'https://gmers.gujarat.gov.in',
    notification_url: 'https://gmers.gujarat.gov.in/career/nurse2024.pdf',
  },

  // ── Jaipur / Rajasthan ──────────────────────────────────────────────────
  {
    title: 'Constable (Rajasthan Police)',
    organization: 'Rajasthan Police',
    category: 'State Govt',
    state: 'Rajasthan',
    district: 'Jaipur',
    city: 'Jaipur',
    lat: 26.9124,
    lon: 75.7873,
    last_date: '2025-04-25',
    status: 'active',
    vacancies: 13913,
    apply_url: 'https://police.rajasthan.gov.in',
    notification_url: 'https://police.rajasthan.gov.in/constable_recruitment_2024.pdf',
  },
  {
    title: 'Patwari (Rajasthan RSMSSB)',
    organization: 'Rajasthan Staff Selection Board',
    category: 'State Govt',
    state: 'Rajasthan',
    district: 'Jaipur',
    city: 'Jaipur',
    lat: 26.9195,
    lon: 75.7891,
    last_date: '2025-02-15',
    status: 'closed',
    vacancies: 3896,
    apply_url: 'https://rsmssb.rajasthan.gov.in',
    notification_url: 'https://rsmssb.rajasthan.gov.in/page?menuName=Advt',
  },

  // ── Lucknow / Uttar Pradesh ─────────────────────────────────────────────
  {
    title: 'UPPSC PCS (Provincial Civil Service)',
    organization: 'Uttar Pradesh PSC',
    category: 'State Govt',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    city: 'Lucknow',
    lat: 26.8467,
    lon: 80.9462,
    last_date: '2025-06-01',
    status: 'upcoming',
    vacancies: 220,
    apply_url: 'https://uppsc.up.nic.in',
    notification_url: 'https://uppsc.up.nic.in/Advts/PCS_2024_Notification.pdf',
  },
  {
    title: 'UP Lekhpal (Revenue Dept)',
    organization: 'UP Revenue Board',
    category: 'State Govt',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    city: 'Lucknow',
    lat: 26.8595,
    lon: 80.9512,
    last_date: '2025-03-28',
    status: 'active',
    vacancies: 8085,
    apply_url: 'https://upsssc.gov.in',
    notification_url: 'https://upsssc.gov.in/PdfFiles/Lekhpal_Advt_2024.pdf',
  },

  // ── Bhopal / Madhya Pradesh ─────────────────────────────────────────────
  {
    title: 'Patwari (MP Vyapam)',
    organization: 'MP Professional Examination Board',
    category: 'State Govt',
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    city: 'Bhopal',
    lat: 23.2599,
    lon: 77.4126,
    last_date: '2025-04-10',
    status: 'active',
    vacancies: 6755,
    apply_url: 'https://peb.mp.gov.in',
    notification_url: 'https://peb.mp.gov.in/Notices/patwari_advt_2024.pdf',
  },

  // ── Patna / Bihar ───────────────────────────────────────────────────────
  {
    title: 'Bihar BPSC 70th Combined',
    organization: 'Bihar Public Service Commission',
    category: 'State Govt',
    state: 'Bihar',
    district: 'Patna',
    city: 'Patna',
    lat: 25.5941,
    lon: 85.1376,
    last_date: '2025-05-20',
    status: 'upcoming',
    vacancies: 1957,
    apply_url: 'https://bpsc.bih.nic.in',
    notification_url: 'https://bpsc.bih.nic.in/Advt/bpsc70cc_notification.pdf',
  },
  {
    title: 'Bihar Police Constable (CSBC)',
    organization: 'Central Selection Board of Constable',
    category: 'State Govt',
    state: 'Bihar',
    district: 'Patna',
    city: 'Patna',
    lat: 25.6087,
    lon: 85.1235,
    last_date: '2025-04-01',
    status: 'active',
    vacancies: 21391,
    apply_url: 'https://csbc.bih.nic.in',
    notification_url: 'https://csbc.bih.nic.in/constable2024.pdf',
  },

  // ── Bhubaneswar / Odisha ────────────────────────────────────────────────
  {
    title: 'OPSC OAS (Odisha Administrative Service)',
    organization: 'Odisha Public Service Commission',
    category: 'State Govt',
    state: 'Odisha',
    district: 'Khordha',
    city: 'Bhubaneswar',
    lat: 20.2961,
    lon: 85.8245,
    last_date: '2025-03-30',
    status: 'active',
    vacancies: 340,
    apply_url: 'https://opsc.gov.in',
    notification_url: 'https://opsc.gov.in/Notification/OAS_2024.pdf',
  },

  // ── Chandigarh / Punjab cluster ─────────────────────────────────────────
  {
    title: 'Naib Tehsildar (PPSC Punjab)',
    organization: 'Punjab Public Service Commission',
    category: 'State Govt',
    state: 'Punjab',
    district: 'Mohali',
    city: 'Chandigarh',
    lat: 30.7333,
    lon: 76.7794,
    last_date: '2025-04-08',
    status: 'active',
    vacancies: 76,
    apply_url: 'https://ppsc.gov.in',
    notification_url: 'https://ppsc.gov.in/Uploads/Notifications/naib_tehsildar_2024.pdf',
  },
  {
    title: 'Punjab Police Sub Inspector',
    organization: 'Punjab Police',
    category: 'State Govt',
    state: 'Punjab',
    district: 'Ludhiana',
    city: 'Ludhiana',
    lat: 30.9010,
    lon: 75.8573,
    last_date: '2025-05-25',
    status: 'upcoming',
    vacancies: 1000,
    apply_url: 'https://ppsc.gov.in',
    notification_url: 'https://ppsc.gov.in/Uploads/Notifications/si_2024.pdf',
  },

  // ── Indian Railways (pan-India) ─────────────────────────────────────────
  {
    title: 'RRB NTPC Graduate Posts',
    organization: 'Railway Recruitment Boards',
    category: 'Railway',
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    lat: 28.6434,
    lon: 77.2167,
    last_date: '2025-07-01',
    status: 'upcoming',
    vacancies: 11558,
    apply_url: 'https://www.rrbapply.gov.in',
    notification_url: 'https://rrbapply.gov.in/notifications/ntpc-grad-2024.pdf',
  },
  {
    title: 'RRB JE (Junior Engineer)',
    organization: 'Railway Recruitment Boards',
    category: 'Railway',
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    lat: 28.6412,
    lon: 77.2148,
    last_date: '2025-07-15',
    status: 'upcoming',
    vacancies: 7951,
    apply_url: 'https://www.rrbapply.gov.in',
    notification_url: 'https://rrbapply.gov.in/notifications/je-2024.pdf',
  },
  {
    title: 'Group D Level 1 (RRB)',
    organization: 'Railway Recruitment Boards',
    category: 'Railway',
    state: 'Maharashtra',
    district: 'Mumbai',
    city: 'Mumbai',
    lat: 19.0626,
    lon: 72.8367,
    last_date: '2025-06-30',
    status: 'upcoming',
    vacancies: 103769,
    apply_url: 'https://www.rrbapply.gov.in',
    notification_url: 'https://rrbapply.gov.in/notifications/groupd-2024.pdf',
  },

  // ── Banking / IBPS ──────────────────────────────────────────────────────
  {
    title: 'IBPS PO (Probationary Officer)',
    organization: 'Institute of Banking Personnel Selection',
    category: 'Banking',
    state: 'Maharashtra',
    district: 'Mumbai',
    city: 'Mumbai',
    lat: 18.9668,
    lon: 72.8317,
    last_date: '2025-08-15',
    status: 'upcoming',
    vacancies: 4455,
    apply_url: 'https://www.ibps.in',
    notification_url: 'https://www.ibps.in/wp-content/uploads/Advertisement-IBPS-PO-2024.pdf',
  },
  {
    title: 'IBPS Clerk',
    organization: 'Institute of Banking Personnel Selection',
    category: 'Banking',
    state: 'Maharashtra',
    district: 'Mumbai',
    city: 'Mumbai',
    lat: 18.9697,
    lon: 72.8349,
    last_date: '2025-09-01',
    status: 'upcoming',
    vacancies: 6128,
    apply_url: 'https://www.ibps.in',
    notification_url: 'https://www.ibps.in/wp-content/uploads/IBPS-Clerk-2024.pdf',
  },
  {
    title: 'SBI PO (Probationary Officer)',
    organization: 'State Bank of India',
    category: 'Banking',
    state: 'Maharashtra',
    district: 'Mumbai',
    city: 'Mumbai',
    lat: 18.9245,
    lon: 72.8318,
    last_date: '2025-04-30',
    status: 'active',
    vacancies: 2000,
    apply_url: 'https://sbi.co.in/careers',
    notification_url: 'https://sbi.co.in/documents/SBI-PO-2024.pdf',
  },
  {
    title: 'SBI Clerk (Junior Associate)',
    organization: 'State Bank of India',
    category: 'Banking',
    state: 'Maharashtra',
    district: 'Mumbai',
    city: 'Mumbai',
    lat: 18.9221,
    lon: 72.8298,
    last_date: '2025-05-10',
    status: 'upcoming',
    vacancies: 13735,
    apply_url: 'https://sbi.co.in/careers',
    notification_url: 'https://sbi.co.in/documents/SBI-Clerk-2024.pdf',
  },

  // ── Defence ─────────────────────────────────────────────────────────────
  {
    title: 'Indian Army Agniveer (Tech)',
    organization: 'Indian Army',
    category: 'Defence',
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    lat: 28.6366,
    lon: 77.2078,
    last_date: '2025-03-10',
    status: 'active',
    vacancies: 25000,
    apply_url: 'https://joinindianarmy.nic.in',
    notification_url: 'https://joinindianarmy.nic.in/agniveer_tech_2024.pdf',
  },
  {
    title: 'Indian Navy Agniveer (SSR)',
    organization: 'Indian Navy',
    category: 'Defence',
    state: 'Maharashtra',
    district: 'Mumbai',
    city: 'Mumbai',
    lat: 18.9218,
    lon: 72.8347,
    last_date: '2025-03-20',
    status: 'active',
    vacancies: 2800,
    apply_url: 'https://joinindiannavy.gov.in',
    notification_url: 'https://joinindiannavy.gov.in/agniveer_ssr_2024.pdf',
  },
  {
    title: 'Indian Coast Guard Navik GD',
    organization:'Indian Coast Guard',
    category: 'Defence',
    state: 'Tamil Nadu',
    district: 'Chennai',
    city: 'Chennai',
    lat: 13.0566,
    lon: 80.2859,
    last_date: '2025-04-15',
    status: 'active',
    vacancies: 350,
    apply_url: 'https://joinindiancoastguard.cdac.in',
    notification_url: 'https://joinindiancoastguard.cdac.in/navik_gd_2024.pdf',
  },

  // ── Teaching / Education ────────────────────────────────────────────────
  {
    title: 'UP Assistant Teacher (UP TET)',
    organization: 'Uttar Pradesh Basic Education Board',
    category: 'Education',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    city: 'Lucknow',
    lat: 26.8422,
    lon: 80.9351,
    last_date: '2025-06-15',
    status: 'upcoming',
    vacancies: 51112,
    apply_url: 'https://updeled.gov.in',
    notification_url: 'https://updeled.gov.in/tet2024.pdf',
  },
  {
    title: 'Kendriya Vidyalaya PGT/TGT/PRT',
    organization: 'Kendriya Vidyalaya Sangathan',
    category: 'Education',
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    lat: 28.6023,
    lon: 77.1987,
    last_date: '2025-05-05',
    status: 'upcoming',
    vacancies: 13404,
    apply_url: 'https://kvsangathan.nic.in',
    notification_url: 'https://kvsangathan.nic.in/teacher2024.pdf',
  },

  // ── Health ──────────────────────────────────────────────────────────────
  {
    title: 'Staff Nurse (AIIMS New Delhi)',
    organization: 'All India Institute of Medical Sciences',
    category: 'Health',
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    lat: 28.5674,
    lon: 77.21,
    last_date: '2025-03-22',
    status: 'active',
    vacancies: 3000,
    apply_url: 'https://aiimsexams.ac.in',
    notification_url: 'https://aiimsexams.ac.in/pdf/nursing_officer_2024.pdf',
  },
  {
    title: 'Community Health Officer (NRHM)',
    organization: 'National Rural Health Mission',
    category: 'Health',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    city: 'Lucknow',
    lat: 26.8475,
    lon: 80.9389,
    last_date: '2025-04-28',
    status: 'active',
    vacancies: 5210,
    apply_url: 'https://upnrhm.gov.in',
    notification_url: 'https://upnrhm.gov.in/cho_2024.pdf',
  },

  // ── Miscellaneous PSUs ──────────────────────────────────────────────────
  {
    title: 'ISRO Scientist/Engineer SC',
    organization: 'Indian Space Research Organisation',
    category: 'PSU',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    lat: 13.0354,
    lon: 77.5706,
    last_date: '2025-03-05',
    status: 'active',
    vacancies: 303,
    apply_url: 'https://www.isro.gov.in/Recruitment',
    notification_url: 'https://www.isro.gov.in/sites/default/files/scientist_sc_2024.pdf',
  },
  {
    title: 'DRDO Junior Research Fellow',
    organization: 'Defence Research and Development Organisation',
    category: 'PSU',
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    lat: 28.6271,
    lon: 77.2041,
    last_date: '2025-04-20',
    status: 'active',
    vacancies: 1817,
    apply_url: 'https://rac.gov.in',
    notification_url: 'https://rac.gov.in/jrf_2024_notification.pdf',
  },
  {
    title: 'ONGC GET (Graduate Executive Trainee)',
    organization: 'Oil and Natural Gas Corporation',
    category: 'PSU',
    state: 'Uttarakhand',
    district: 'Dehradun',
    city: 'Dehradun',
    lat: 30.3165,
    lon: 78.0322,
    last_date: '2025-05-10',
    status: 'upcoming',
    vacancies: 1225,
    apply_url: 'https://www.ongcindia.com',
    notification_url: 'https://www.ongcindia.com/wps/wcm/connect/GET_2024_notification.pdf',
  },
];
/* eslint-enable */

async function seed() {
  console.log(`Seeding ${JOBS.length} jobs...`);

  const { error } = await supabase.from('jobs').upsert(
    JOBS.map((job) => ({
      ...job,
      last_date: job.last_date,
    })),
    { onConflict: 'title,organization' }
  );

  if (error) {
    console.error('Seed error:', error);
    process.exit(1);
  }

  console.log('Seed complete.');
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
