'use strict';

/**
 * Seed script: inserts 40 realistic sample govt jobs across Indian states.
 *
 * Usage:
 *   DATABASE_URL=postgresql://... node backend/seeds/seed_jobs.js
 *   – or –
 *   cd backend && npm run seed
 */

require('dotenv').config({ path: require('path').join(__dirname, '../../.env') });

const crypto = require('crypto');
const { Pool } = require('pg');

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false,
});

function hash(title, org, url) {
  return crypto
    .createHash('sha256')
    .update(`${title.toLowerCase().trim()}||${org.toLowerCase().trim()}||${url}`)
    .digest('hex');
}

// 40 realistic sample govt jobs spread across Indian states
const JOBS = [
  {
    title: 'Junior Engineer (Civil)',
    organisation: 'Public Works Department, Maharashtra',
    category: 'Engineering',
    qualification: 'Graduate',
    state: 'Maharashtra',
    district: 'Mumbai',
    lat: 19.0760, lon: 72.8777,
    location_label: 'Mumbai, Maharashtra',
    vacancies: 350,
    salary: '₹35,400 – ₹1,12,400',
    apply_start_date: '2024-11-01',
    apply_end_date: '2024-12-31',
    status: 'open',
    official_notification_url: 'https://mahaonline.gov.in/notices/je-civil-2024.pdf',
    source_url: 'https://mahaonline.gov.in',
    description: 'Recruitment for Junior Engineer (Civil) under Public Works Department, Maharashtra.',
  },
  {
    title: 'Sub-Inspector (Executive)',
    organisation: 'Delhi Police',
    category: 'Police',
    qualification: 'Graduate',
    state: 'Delhi',
    district: 'New Delhi',
    lat: 28.6139, lon: 77.2090,
    location_label: 'New Delhi, Delhi',
    vacancies: 698,
    salary: '₹35,400 – ₹1,12,400',
    apply_start_date: '2024-10-15',
    apply_end_date: '2024-11-15',
    status: 'open',
    official_notification_url: 'https://delhipolice.gov.in/recruitment/si-exec-2024.pdf',
    source_url: 'https://delhipolice.gov.in/recruitment',
    description: 'Delhi Police Sub-Inspector Executive Recruitment 2024.',
  },
  {
    title: 'Constable (GD) CISF',
    organisation: 'Central Industrial Security Force',
    category: 'Defence & Security',
    qualification: '10th',
    state: 'Central',
    district: null,
    lat: 20.5937, lon: 78.9629,
    location_label: 'All India',
    vacancies: 1130,
    salary: '₹21,700 – ₹69,100',
    apply_start_date: '2024-09-01',
    apply_end_date: '2024-10-30',
    status: 'open',
    official_notification_url: 'https://ssc.gov.in/notices/cisf-gd-2024.pdf',
    source_url: 'https://ssc.gov.in',
    description: 'SSC Constable GD in CISF Recruitment 2024.',
  },
  {
    title: 'Staff Nurse Grade II',
    organisation: 'AIIMS New Delhi',
    category: 'Health',
    qualification: 'Graduate',
    state: 'Delhi',
    district: 'New Delhi',
    lat: 28.5672, lon: 77.2100,
    location_label: 'New Delhi, Delhi',
    vacancies: 520,
    salary: '₹44,900 – ₹1,42,400',
    apply_start_date: '2024-11-10',
    apply_end_date: '2025-01-10',
    status: 'open',
    official_notification_url: 'https://aiims.edu/recruitment/nurse-2024.pdf',
    source_url: 'https://aiims.edu/recruitment',
    description: 'AIIMS New Delhi Staff Nurse Grade II Recruitment 2024.',
  },
  {
    title: 'Probationary Officer',
    organisation: 'State Bank of India',
    category: 'Banking',
    qualification: 'Graduate',
    state: 'Central',
    district: null,
    lat: 18.9220, lon: 72.8347,
    location_label: 'All India',
    vacancies: 2000,
    salary: '₹41,960 – ₹63,840',
    apply_start_date: '2024-10-01',
    apply_end_date: '2024-11-01',
    status: 'open',
    official_notification_url: 'https://sbi.co.in/careers/po-2024.pdf',
    source_url: 'https://sbi.co.in/careers',
    description: 'SBI PO Recruitment 2024 – 2000 vacancies.',
  },
  {
    title: 'Assistant Loco Pilot (ALP)',
    organisation: 'Indian Railways – South Central Railway',
    category: 'Railway',
    qualification: 'ITI',
    state: 'Telangana',
    district: 'Hyderabad',
    lat: 17.3850, lon: 78.4867,
    location_label: 'Hyderabad, Telangana',
    vacancies: 5696,
    salary: '₹19,900 – ₹63,200',
    apply_start_date: '2024-08-01',
    apply_end_date: '2024-09-30',
    status: 'open',
    official_notification_url: 'https://rrbscr.gov.in/alp-2024.pdf',
    source_url: 'https://rrbscr.gov.in',
    description: 'RRB ALP Recruitment 2024 – South Central Railway.',
  },
  {
    title: 'Group D Multitasking Staff',
    organisation: 'Indian Railways – Northern Railway',
    category: 'Railway',
    qualification: '10th',
    state: 'Delhi',
    district: 'New Delhi',
    lat: 28.6448, lon: 77.2167,
    location_label: 'New Delhi, Delhi',
    vacancies: 103769,
    salary: '₹18,000 – ₹56,900',
    apply_start_date: '2024-07-01',
    apply_end_date: '2024-08-31',
    status: 'open',
    official_notification_url: 'https://rrbnr.indianrailways.gov.in/groupd-2024.pdf',
    source_url: 'https://rrbnr.indianrailways.gov.in',
    description: 'RRB Group D Recruitment 2024 – Northern Railway.',
  },
  {
    title: 'UPSC Civil Services (IAS/IPS/IFS)',
    organisation: 'Union Public Service Commission',
    category: 'Civil Services',
    qualification: 'Graduate',
    state: 'Central',
    district: null,
    lat: 28.6225, lon: 77.2150,
    location_label: 'All India',
    vacancies: 1056,
    salary: '₹56,100 – ₹2,50,000',
    apply_start_date: '2025-02-05',
    apply_end_date: '2025-03-04',
    status: 'upcoming',
    official_notification_url: 'https://upsc.gov.in/examinations/cse-2025.pdf',
    source_url: 'https://upsc.gov.in',
    description: 'UPSC Civil Services Examination 2025.',
  },
  {
    title: 'Junior Accountant',
    organisation: 'Rajasthan State Government',
    category: 'Accounts & Finance',
    qualification: 'Graduate',
    state: 'Rajasthan',
    district: 'Jaipur',
    lat: 26.9124, lon: 75.7873,
    location_label: 'Jaipur, Rajasthan',
    vacancies: 2874,
    salary: '₹29,200 – ₹92,300',
    apply_start_date: '2024-12-01',
    apply_end_date: '2025-01-31',
    status: 'open',
    official_notification_url: 'https://rsmssb.rajasthan.gov.in/jr-accountant-2024.pdf',
    source_url: 'https://rsmssb.rajasthan.gov.in',
    description: 'RSMSSB Junior Accountant Recruitment 2024.',
  },
  {
    title: 'Assistant Engineer (Electrical)',
    organisation: 'Tamil Nadu Public Service Commission',
    category: 'Engineering',
    qualification: 'Graduate',
    state: 'Tamil Nadu',
    district: 'Chennai',
    lat: 13.0827, lon: 80.2707,
    location_label: 'Chennai, Tamil Nadu',
    vacancies: 1246,
    salary: '₹56,100 – ₹1,77,500',
    apply_start_date: '2024-11-15',
    apply_end_date: '2025-01-15',
    status: 'open',
    official_notification_url: 'https://tnpsc.gov.in/ae-elec-2024.pdf',
    source_url: 'https://tnpsc.gov.in',
    description: 'TNPSC Assistant Engineer (Electrical) Recruitment 2024.',
  },
  {
    title: 'Forest Guard',
    organisation: 'Uttarakhand Forest Department',
    category: 'Forest',
    qualification: '12th',
    state: 'Uttarakhand',
    district: 'Dehradun',
    lat: 30.3165, lon: 78.0322,
    location_label: 'Dehradun, Uttarakhand',
    vacancies: 894,
    salary: '₹21,700 – ₹69,100',
    apply_start_date: '2024-10-10',
    apply_end_date: '2024-11-30',
    status: 'open',
    official_notification_url: 'https://ukforest.gov.in/guard-2024.pdf',
    source_url: 'https://ukforest.gov.in',
    description: 'Uttarakhand Forest Guard Recruitment 2024.',
  },
  {
    title: 'SSC CGL (Combined Graduate Level)',
    organisation: 'Staff Selection Commission',
    category: 'Government',
    qualification: 'Graduate',
    state: 'Central',
    district: null,
    lat: 28.6139, lon: 77.2090,
    location_label: 'All India',
    vacancies: 17727,
    salary: '₹25,500 – ₹81,100',
    apply_start_date: '2024-06-24',
    apply_end_date: '2024-07-24',
    status: 'closed',
    official_notification_url: 'https://ssc.gov.in/cgl-2024.pdf',
    source_url: 'https://ssc.gov.in',
    description: 'SSC CGL 2024 recruitment across multiple posts.',
  },
  {
    title: 'Primary Teacher (PRT)',
    organisation: 'Kendriya Vidyalaya Sangathan',
    category: 'Teaching',
    qualification: 'Graduate',
    state: 'Central',
    district: null,
    lat: 28.5918, lon: 77.1667,
    location_label: 'All India',
    vacancies: 13404,
    salary: '₹35,400 – ₹1,12,400',
    apply_start_date: '2024-12-01',
    apply_end_date: '2025-01-20',
    status: 'open',
    official_notification_url: 'https://kvsangathan.nic.in/prt-2024.pdf',
    source_url: 'https://kvsangathan.nic.in',
    description: 'KVS PRT Recruitment 2024.',
  },
  {
    title: 'Inspector (Income Tax)',
    organisation: 'Income Tax Department – West Bengal',
    category: 'Finance & Tax',
    qualification: 'Graduate',
    state: 'West Bengal',
    district: 'Kolkata',
    lat: 22.5726, lon: 88.3639,
    location_label: 'Kolkata, West Bengal',
    vacancies: 125,
    salary: '₹44,900 – ₹1,42,400',
    apply_start_date: '2024-11-20',
    apply_end_date: '2024-12-20',
    status: 'open',
    official_notification_url: 'https://incometaxindia.gov.in/wb-inspector-2024.pdf',
    source_url: 'https://incometaxindia.gov.in',
    description: 'Income Tax Inspector Recruitment 2024 – West Bengal.',
  },
  {
    title: 'Scientific Officer (Chemistry)',
    organisation: 'Central Forensic Science Laboratory',
    category: 'Science & Research',
    qualification: 'Post Graduate',
    state: 'Gujarat',
    district: 'Ahmedabad',
    lat: 23.0225, lon: 72.5714,
    location_label: 'Ahmedabad, Gujarat',
    vacancies: 42,
    salary: '₹56,100 – ₹1,77,500',
    apply_start_date: '2024-10-05',
    apply_end_date: '2024-11-05',
    status: 'closed',
    official_notification_url: 'https://cfsl.gov.in/so-chem-2024.pdf',
    source_url: 'https://cfsl.gov.in',
    description: 'CFSL Scientific Officer (Chemistry) Recruitment 2024.',
  },
  {
    title: 'Pharmacist Grade II',
    organisation: 'Government Medical College, Nagpur',
    category: 'Health',
    qualification: 'Graduate',
    state: 'Maharashtra',
    district: 'Nagpur',
    lat: 21.1458, lon: 79.0882,
    location_label: 'Nagpur, Maharashtra',
    vacancies: 60,
    salary: '₹29,200 – ₹92,300',
    apply_start_date: '2024-12-10',
    apply_end_date: '2025-01-09',
    status: 'open',
    official_notification_url: 'https://gmcnagpur.edu.in/pharmacist-2024.pdf',
    source_url: 'https://gmcnagpur.edu.in',
    description: 'Pharmacist Grade II Recruitment – GMC Nagpur.',
  },
  {
    title: 'Librarian Grade III',
    organisation: 'Madhya Pradesh Public Service Commission',
    category: 'Library & Documentation',
    qualification: 'Graduate',
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    lat: 23.2599, lon: 77.4126,
    location_label: 'Bhopal, Madhya Pradesh',
    vacancies: 139,
    salary: '₹29,200 – ₹92,300',
    apply_start_date: '2024-11-01',
    apply_end_date: '2024-12-15',
    status: 'open',
    official_notification_url: 'https://mppscdemo.mp.gov.in/librarian-2024.pdf',
    source_url: 'https://mppscdemo.mp.gov.in',
    description: 'MPPSC Librarian Grade III Recruitment 2024.',
  },
  {
    title: 'Clerk-cum-Typist',
    organisation: 'High Court of Punjab & Haryana',
    category: 'Judiciary',
    qualification: '12th',
    state: 'Punjab',
    district: 'Chandigarh',
    lat: 30.7333, lon: 76.7794,
    location_label: 'Chandigarh, Punjab',
    vacancies: 760,
    salary: '₹19,900 – ₹63,200',
    apply_start_date: '2024-12-05',
    apply_end_date: '2025-01-04',
    status: 'open',
    official_notification_url: 'https://highcourtchd.gov.in/clerk-2024.pdf',
    source_url: 'https://highcourtchd.gov.in',
    description: 'Punjab & Haryana High Court Clerk-cum-Typist Recruitment 2024.',
  },
  {
    title: 'Livestock Inspector',
    organisation: 'Animal Husbandry Department, Bihar',
    category: 'Agriculture & Allied',
    qualification: '12th',
    state: 'Bihar',
    district: 'Patna',
    lat: 25.5941, lon: 85.1376,
    location_label: 'Patna, Bihar',
    vacancies: 1149,
    salary: '₹25,500 – ₹81,100',
    apply_start_date: '2024-10-20',
    apply_end_date: '2024-11-19',
    status: 'open',
    official_notification_url: 'https://bpsc.bih.nic.in/lsi-2024.pdf',
    source_url: 'https://bpsc.bih.nic.in',
    description: 'Bihar Livestock Inspector Recruitment 2024.',
  },
  {
    title: 'Revenue Inspector',
    organisation: 'Assam Revenue Department',
    category: 'Revenue',
    qualification: 'Graduate',
    state: 'Assam',
    district: 'Guwahati',
    lat: 26.1445, lon: 91.7362,
    location_label: 'Guwahati, Assam',
    vacancies: 300,
    salary: '₹14,000 – ₹60,500',
    apply_start_date: '2024-12-01',
    apply_end_date: '2024-12-31',
    status: 'open',
    official_notification_url: 'https://slrc-assam.org/ri-2024.pdf',
    source_url: 'https://slrc-assam.org',
    description: 'Assam Revenue Inspector Recruitment 2024.',
  },
  {
    title: 'Junior Research Fellow (JRF)',
    organisation: 'ISRO – Space Applications Centre',
    category: 'Science & Research',
    qualification: 'Post Graduate',
    state: 'Gujarat',
    district: 'Ahmedabad',
    lat: 23.0225, lon: 72.5714,
    location_label: 'Ahmedabad, Gujarat',
    vacancies: 25,
    salary: '₹31,000 (Stipend)',
    apply_start_date: '2024-11-25',
    apply_end_date: '2024-12-25',
    status: 'open',
    official_notification_url: 'https://sac.gov.in/jrf-2024.pdf',
    source_url: 'https://sac.gov.in',
    description: 'ISRO SAC Junior Research Fellow Recruitment 2024.',
  },
  {
    title: 'Anganwadi Worker / Helper',
    organisation: 'Women & Child Development, Uttar Pradesh',
    category: 'Social Welfare',
    qualification: '10th',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    lat: 26.8467, lon: 80.9462,
    location_label: 'Lucknow, Uttar Pradesh',
    vacancies: 53000,
    salary: '₹4,000 – ₹8,000 (Honorarium)',
    apply_start_date: '2024-09-01',
    apply_end_date: '2024-11-01',
    status: 'closed',
    official_notification_url: 'https://balvikasup.gov.in/anganwadi-2024.pdf',
    source_url: 'https://balvikasup.gov.in',
    description: 'UP Anganwadi Worker and Helper Recruitment 2024.',
  },
  {
    title: 'Marine Engineer Officer',
    organisation: 'Shipping Corporation of India',
    category: 'Maritime',
    qualification: 'Graduate',
    state: 'Maharashtra',
    district: 'Mumbai',
    lat: 18.9490, lon: 72.8423,
    location_label: 'Mumbai, Maharashtra',
    vacancies: 48,
    salary: '₹80,000 – ₹2,50,000',
    apply_start_date: '2024-12-10',
    apply_end_date: '2025-01-09',
    status: 'open',
    official_notification_url: 'https://shipindia.com/recruitment/marine-2024.pdf',
    source_url: 'https://shipindia.com/recruitment',
    description: 'SCI Marine Engineer Officer Recruitment 2024.',
  },
  {
    title: 'Assistant Section Officer',
    organisation: 'Kerala Public Service Commission',
    category: 'Government',
    qualification: 'Graduate',
    state: 'Kerala',
    district: 'Thiruvananthapuram',
    lat: 8.5241, lon: 76.9366,
    location_label: 'Thiruvananthapuram, Kerala',
    vacancies: 54,
    salary: '₹41,300 – ₹1,21,700',
    apply_start_date: '2024-11-15',
    apply_end_date: '2025-01-14',
    status: 'open',
    official_notification_url: 'https://psc.kerala.gov.in/aso-2024.pdf',
    source_url: 'https://psc.kerala.gov.in',
    description: 'Kerala PSC Assistant Section Officer Recruitment 2024.',
  },
  {
    title: 'Assistant Conservator of Forests',
    organisation: 'Karnataka Forest Department',
    category: 'Forest',
    qualification: 'Graduate',
    state: 'Karnataka',
    district: 'Bengaluru',
    lat: 12.9716, lon: 77.5946,
    location_label: 'Bengaluru, Karnataka',
    vacancies: 42,
    salary: '₹35,400 – ₹1,12,400',
    apply_start_date: '2025-01-05',
    apply_end_date: '2025-02-05',
    status: 'upcoming',
    official_notification_url: 'https://kpsc.kar.nic.in/acf-2025.pdf',
    source_url: 'https://kpsc.kar.nic.in',
    description: 'Karnataka PSC ACF Recruitment 2025.',
  },
  {
    title: 'Data Entry Operator Grade B',
    organisation: 'National Informatics Centre (NIC)',
    category: 'IT & Technology',
    qualification: '12th',
    state: 'Central',
    district: null,
    lat: 28.6288, lon: 77.2166,
    location_label: 'All India',
    vacancies: 320,
    salary: '₹25,500 – ₹81,100',
    apply_start_date: '2024-11-20',
    apply_end_date: '2024-12-20',
    status: 'open',
    official_notification_url: 'https://nic.in/careers/deo-2024.pdf',
    source_url: 'https://nic.in/careers',
    description: 'NIC Data Entry Operator Grade B Recruitment 2024.',
  },
  {
    title: 'Patwari (Village Accountant)',
    organisation: 'Revenue Department, Himachal Pradesh',
    category: 'Revenue',
    qualification: '12th',
    state: 'Himachal Pradesh',
    district: 'Shimla',
    lat: 31.1048, lon: 77.1734,
    location_label: 'Shimla, Himachal Pradesh',
    vacancies: 1073,
    salary: '₹10,300 – ₹34,800',
    apply_start_date: '2024-12-05',
    apply_end_date: '2025-01-04',
    status: 'open',
    official_notification_url: 'https://hpsssc.hp.gov.in/patwari-2024.pdf',
    source_url: 'https://hpsssc.hp.gov.in',
    description: 'HP Patwari Recruitment 2024.',
  },
  {
    title: 'Technical Assistant (Geology)',
    organisation: 'Geological Survey of India',
    category: 'Science & Research',
    qualification: 'Graduate',
    state: 'Central',
    district: null,
    lat: 22.5726, lon: 88.3639,
    location_label: 'All India',
    vacancies: 116,
    salary: '₹35,400 – ₹1,12,400',
    apply_start_date: '2025-01-10',
    apply_end_date: '2025-02-09',
    status: 'upcoming',
    official_notification_url: 'https://gsi.gov.in/ta-geology-2025.pdf',
    source_url: 'https://gsi.gov.in',
    description: 'GSI Technical Assistant (Geology) Recruitment 2025.',
  },
  {
    title: 'Inspector (General Central Service)',
    organisation: 'Central Goods & Services Tax Department',
    category: 'Finance & Tax',
    qualification: 'Graduate',
    state: 'Central',
    district: null,
    lat: 28.6139, lon: 77.2090,
    location_label: 'All India',
    vacancies: 900,
    salary: '₹44,900 – ₹1,42,400',
    apply_start_date: '2024-10-01',
    apply_end_date: '2024-11-01',
    status: 'closed',
    official_notification_url: 'https://ssc.gov.in/cgl-inspector-gst-2024.pdf',
    source_url: 'https://ssc.gov.in',
    description: 'Inspector (CGST & Central Excise) via SSC CGL 2024.',
  },
  {
    title: 'Pilot (Commercial)',
    organisation: 'Air India – AISATS',
    category: 'Aviation',
    qualification: 'Graduate',
    state: 'Delhi',
    district: 'New Delhi',
    lat: 28.5562, lon: 77.0998,
    location_label: 'New Delhi, Delhi',
    vacancies: 30,
    salary: '₹2,00,000 – ₹4,00,000',
    apply_start_date: '2024-12-15',
    apply_end_date: '2025-01-14',
    status: 'open',
    official_notification_url: 'https://airindia.in/careers/pilot-2024.pdf',
    source_url: 'https://airindia.in/careers',
    description: 'Air India Commercial Pilot Recruitment 2024.',
  },
  {
    title: 'Territorial Army Officer',
    organisation: 'Indian Army – Territorial Army Directorate',
    category: 'Defence & Security',
    qualification: 'Graduate',
    state: 'Central',
    district: null,
    lat: 28.5918, lon: 77.1667,
    location_label: 'All India',
    vacancies: 150,
    salary: '₹56,100 – ₹2,50,000 (Service)',
    apply_start_date: '2025-01-15',
    apply_end_date: '2025-02-15',
    status: 'upcoming',
    official_notification_url: 'https://jointerritorialarmy.gov.in/ta-officer-2025.pdf',
    source_url: 'https://jointerritorialarmy.gov.in',
    description: 'Territorial Army Officer Entry Scheme 2025.',
  },
  {
    title: 'Junior Analyst (Chemical)',
    organisation: 'Drug Control Department, Odisha',
    category: 'Health',
    qualification: 'Post Graduate',
    state: 'Odisha',
    district: 'Bhubaneswar',
    lat: 20.2961, lon: 85.8245,
    location_label: 'Bhubaneswar, Odisha',
    vacancies: 20,
    salary: '₹35,400 – ₹1,12,400',
    apply_start_date: '2024-11-28',
    apply_end_date: '2024-12-28',
    status: 'open',
    official_notification_url: 'https://opsc.gov.in/jr-analyst-2024.pdf',
    source_url: 'https://opsc.gov.in',
    description: 'OPSC Junior Analyst (Chemical) Recruitment 2024.',
  },
  {
    title: 'Sub-Inspector (Telecom)',
    organisation: 'Border Security Force (BSF)',
    category: 'Defence & Security',
    qualification: 'Graduate',
    state: 'Central',
    district: null,
    lat: 28.6139, lon: 77.2090,
    location_label: 'All India',
    vacancies: 186,
    salary: '₹35,400 – ₹1,12,400',
    apply_start_date: '2024-09-15',
    apply_end_date: '2024-10-15',
    status: 'closed',
    official_notification_url: 'https://rectt.bsf.gov.in/si-telecom-2024.pdf',
    source_url: 'https://rectt.bsf.gov.in',
    description: 'BSF Sub-Inspector Telecom Recruitment 2024.',
  },
  {
    title: 'Women Police Constable',
    organisation: 'Telangana State Police',
    category: 'Police',
    qualification: '12th',
    state: 'Telangana',
    district: 'Hyderabad',
    lat: 17.3850, lon: 78.4867,
    location_label: 'Hyderabad, Telangana',
    vacancies: 2050,
    salary: '₹21,400 – ₹67,700',
    apply_start_date: '2024-12-01',
    apply_end_date: '2025-01-01',
    status: 'open',
    official_notification_url: 'https://tslprb.in/wpc-2024.pdf',
    source_url: 'https://tslprb.in',
    description: 'Telangana Women Police Constable Recruitment 2024.',
  },
  {
    title: 'Agriculture Field Officer',
    organisation: 'Punjab National Bank (PNB)',
    category: 'Banking',
    qualification: 'Graduate',
    state: 'Punjab',
    district: 'Chandigarh',
    lat: 30.7333, lon: 76.7794,
    location_label: 'Chandigarh, Punjab',
    vacancies: 1025,
    salary: '₹36,000 – ₹63,840',
    apply_start_date: '2024-11-05',
    apply_end_date: '2024-12-05',
    status: 'open',
    official_notification_url: 'https://pnbindia.in/careers/afo-2024.pdf',
    source_url: 'https://pnbindia.in/careers',
    description: 'PNB Agriculture Field Officer Recruitment 2024.',
  },
  {
    title: 'Field Investigator',
    organisation: 'National Sample Survey Office (NSSO)',
    category: 'Statistics',
    qualification: '12th',
    state: 'Central',
    district: null,
    lat: 28.6139, lon: 77.2090,
    location_label: 'All India',
    vacancies: 400,
    salary: '₹25,500 – ₹81,100',
    apply_start_date: '2024-12-10',
    apply_end_date: '2025-01-09',
    status: 'open',
    official_notification_url: 'https://mospi.gov.in/nsso-fi-2024.pdf',
    source_url: 'https://mospi.gov.in',
    description: 'NSSO Field Investigator Recruitment 2024.',
  },
  {
    title: 'Gram Rojgar Sevak',
    organisation: 'MGNREGS – Chhattisgarh',
    category: 'Social Welfare',
    qualification: '10th',
    state: 'Chhattisgarh',
    district: 'Raipur',
    lat: 21.2514, lon: 81.6296,
    location_label: 'Raipur, Chhattisgarh',
    vacancies: 2700,
    salary: '₹6,000 – ₹8,000 (Monthly)',
    apply_start_date: '2024-10-25',
    apply_end_date: '2024-11-24',
    status: 'closed',
    official_notification_url: 'https://cgstate.gov.in/mgnregs-grs-2024.pdf',
    source_url: 'https://cgstate.gov.in',
    description: 'Chhattisgarh Gram Rojgar Sevak Recruitment 2024.',
  },
  {
    title: 'Junior Engineer (IT)',
    organisation: 'Jharkhand Staff Selection Commission',
    category: 'IT & Technology',
    qualification: 'Graduate',
    state: 'Jharkhand',
    district: 'Ranchi',
    lat: 23.3441, lon: 85.3096,
    location_label: 'Ranchi, Jharkhand',
    vacancies: 197,
    salary: '₹35,400 – ₹1,12,400',
    apply_start_date: '2024-12-10',
    apply_end_date: '2025-01-09',
    status: 'open',
    official_notification_url: 'https://jssc.nic.in/je-it-2024.pdf',
    source_url: 'https://jssc.nic.in',
    description: 'JSSC Junior Engineer (IT) Recruitment 2024.',
  },
  {
    title: 'Assistant Professor (Computer Science)',
    organisation: 'University of Hyderabad',
    category: 'Teaching',
    qualification: 'Post Graduate',
    state: 'Telangana',
    district: 'Hyderabad',
    lat: 17.4107, lon: 78.4536,
    location_label: 'Hyderabad, Telangana',
    vacancies: 8,
    salary: '₹57,700 – ₹1,82,400',
    apply_start_date: '2025-01-01',
    apply_end_date: '2025-02-01',
    status: 'upcoming',
    official_notification_url: 'https://uohyd.ac.in/ap-cs-2025.pdf',
    source_url: 'https://uohyd.ac.in',
    description: 'University of Hyderabad Assistant Professor (CS) Recruitment 2025.',
  },
  {
    title: 'Naib Tehsildar',
    organisation: 'Himachal Pradesh Administrative Tribunal',
    category: 'Revenue',
    qualification: 'Graduate',
    state: 'Himachal Pradesh',
    district: 'Shimla',
    lat: 31.1048, lon: 77.1734,
    location_label: 'Shimla, Himachal Pradesh',
    vacancies: 16,
    salary: '₹10,300 – ₹34,800',
    apply_start_date: '2024-11-01',
    apply_end_date: '2024-12-01',
    status: 'closed',
    official_notification_url: 'https://hppsc.hp.gov.in/naib-tehsildar-2024.pdf',
    source_url: 'https://hppsc.hp.gov.in',
    description: 'HP Naib Tehsildar Recruitment 2024.',
  },
  {
    title: 'Postal Assistant / Sorting Assistant',
    organisation: 'India Post – Andhra Pradesh Circle',
    category: 'Postal',
    qualification: '12th',
    state: 'Andhra Pradesh',
    district: 'Vijayawada',
    lat: 16.5062, lon: 80.6480,
    location_label: 'Vijayawada, Andhra Pradesh',
    vacancies: 1592,
    salary: '₹25,500 – ₹81,100',
    apply_start_date: '2024-11-10',
    apply_end_date: '2024-12-09',
    status: 'open',
    official_notification_url: 'https://appost.in/pa-sa-2024.pdf',
    source_url: 'https://appost.in',
    description: 'India Post AP Circle Postal/Sorting Assistant Recruitment 2024.',
  },
  {
    title: 'Result Out – IBPS PO 2024',
    organisation: 'Institute of Banking Personnel Selection',
    category: 'Banking',
    qualification: 'Graduate',
    state: 'Central',
    district: null,
    lat: 19.0760, lon: 72.8777,
    location_label: 'All India',
    vacancies: 4455,
    salary: '₹41,960 – ₹63,840',
    apply_start_date: '2024-07-01',
    apply_end_date: '2024-07-21',
    status: 'result_out',
    official_notification_url: 'https://ibps.in/po-result-2024.pdf',
    source_url: 'https://ibps.in',
    description: 'IBPS PO 2024 – Result declared.',
  },
];

async function seed() {
  console.log(`Seeding ${JOBS.length} sample jobs…`);

  for (const job of JOBS) {
    const sourceHash = hash(job.title, job.organisation, job.source_url || '');
    await pool.query(
      `INSERT INTO jobs
         (title, organisation, source_url, official_notification_url,
          source_hash, category, qualification, status,
          state, district, lat, lon, location_label,
          vacancies, salary, apply_start_date, apply_end_date, description,
          published_at)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18, NOW())
       ON CONFLICT (source_hash) DO NOTHING`,
      [
        job.title,
        job.organisation,
        job.source_url,
        job.official_notification_url,
        sourceHash,
        job.category,
        job.qualification,
        job.status,
        job.state,
        job.district,
        job.lat,
        job.lon,
        job.location_label,
        job.vacancies,
        job.salary,
        job.apply_start_date,
        job.apply_end_date,
        job.description,
      ]
    );
    process.stdout.write('.');
  }

  console.log('\nDone!');
  await pool.end();
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
