#!/usr/bin/env node
'use strict';

/**
 * Seed script: insert sample government jobs into the jobs table.
 * Usage: node scripts/seed-jobs.js
 *
 * Requires DATABASE_URL in environment (or .env file).
 */

require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });

const { Pool } = require('pg');

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false,
});

const today = new Date();
const daysFromNow = (n) => {
  const d = new Date(today);
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
};
const daysAgo = (n) => daysFromNow(-n);

const JOBS = [
  // ── Uttar Pradesh ──────────────────────────────────────────────────────────
  {
    title: 'Sub-Inspector (Civil Police)',
    organization: 'Uttar Pradesh Police',
    board: 'UPPRPB',
    category: 'state',
    status: 'open',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    city: 'Lucknow',
    location_text: 'Lucknow, Uttar Pradesh',
    lat: 26.8467, lon: 80.9462,
    posted_at: daysAgo(10),
    last_date: daysFromNow(25),
    apply_url: 'https://uppbpb.gov.in',
    notification_url: 'https://uppbpb.gov.in/notification/si-2026',
  },
  {
    title: 'Assistant Teacher (Primary)',
    organization: 'Basic Education Board',
    board: 'UPBEB',
    category: 'state',
    status: 'open',
    state: 'Uttar Pradesh',
    district: 'Varanasi',
    city: 'Varanasi',
    location_text: 'Varanasi, Uttar Pradesh',
    lat: 25.3176, lon: 82.9739,
    posted_at: daysAgo(5),
    last_date: daysFromNow(40),
    apply_url: 'https://updeled.gov.in',
    notification_url: 'https://updeled.gov.in/notification/at-2026',
  },
  {
    title: 'Lekhpal (Revenue Department)',
    organization: 'Revenue Department UP',
    board: 'UPSSSC',
    category: 'state',
    status: 'upcoming',
    state: 'Uttar Pradesh',
    district: 'Agra',
    city: 'Agra',
    location_text: 'Agra, Uttar Pradesh',
    lat: 27.1767, lon: 78.0081,
    posted_at: daysAgo(2),
    last_date: daysFromNow(60),
    apply_url: 'https://upsssc.gov.in',
    notification_url: 'https://upsssc.gov.in/notification/lekhpal-2026',
  },

  // ── Maharashtra ────────────────────────────────────────────────────────────
  {
    title: 'Police Constable',
    organization: 'Maharashtra Police',
    board: 'MPSC',
    category: 'state',
    status: 'open',
    state: 'Maharashtra',
    district: 'Pune',
    city: 'Pune',
    location_text: 'Pune, Maharashtra',
    lat: 18.5204, lon: 73.8567,
    posted_at: daysAgo(8),
    last_date: daysFromNow(15),
    apply_url: 'https://mahapolice.gov.in',
    notification_url: 'https://mahapolice.gov.in/constable-2026',
  },
  {
    title: 'Sales Tax Inspector',
    organization: 'Maharashtra Finance Department',
    board: 'MPSC',
    category: 'state',
    status: 'open',
    state: 'Maharashtra',
    district: 'Mumbai',
    city: 'Mumbai',
    location_text: 'Mumbai, Maharashtra',
    lat: 19.0760, lon: 72.8777,
    posted_at: daysAgo(3),
    last_date: daysFromNow(30),
    apply_url: 'https://mpsc.gov.in',
    notification_url: 'https://mpsc.gov.in/sti-2026',
  },
  {
    title: 'Junior Engineer (Civil)',
    organization: 'MSEDCL',
    board: 'MSEDCL',
    category: 'psu',
    status: 'open',
    state: 'Maharashtra',
    district: 'Nagpur',
    city: 'Nagpur',
    location_text: 'Nagpur, Maharashtra',
    lat: 21.1458, lon: 79.0882,
    posted_at: daysAgo(6),
    last_date: daysFromNow(20),
    apply_url: 'https://msedcl.com',
    notification_url: 'https://msedcl.com/je-civil-2026',
  },

  // ── Rajasthan ──────────────────────────────────────────────────────────────
  {
    title: 'Patwari (Revenue)',
    organization: 'Board of Revenue Rajasthan',
    board: 'RSMSSB',
    category: 'state',
    status: 'open',
    state: 'Rajasthan',
    district: 'Jaipur',
    city: 'Jaipur',
    location_text: 'Jaipur, Rajasthan',
    lat: 26.9124, lon: 75.7873,
    posted_at: daysAgo(15),
    last_date: daysFromNow(10),
    apply_url: 'https://rsmssb.rajasthan.gov.in',
    notification_url: 'https://rsmssb.rajasthan.gov.in/patwari-2026',
  },
  {
    title: 'Gram Sevak',
    organization: 'Rajasthan Panchayati Raj',
    board: 'RSMSSB',
    category: 'state',
    status: 'upcoming',
    state: 'Rajasthan',
    district: 'Jodhpur',
    city: 'Jodhpur',
    location_text: 'Jodhpur, Rajasthan',
    lat: 26.2389, lon: 73.0243,
    posted_at: daysAgo(1),
    last_date: daysFromNow(50),
    apply_url: 'https://rsmssb.rajasthan.gov.in',
    notification_url: 'https://rsmssb.rajasthan.gov.in/gram-sevak-2026',
  },

  // ── Central (UPSC / SSC) ──────────────────────────────────────────────────
  {
    title: 'Combined Defence Services (CDS) – II 2026',
    organization: 'Ministry of Defence',
    board: 'UPSC',
    category: 'central',
    status: 'open',
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    location_text: 'New Delhi',
    lat: 28.6139, lon: 77.2090,
    posted_at: daysAgo(12),
    last_date: daysFromNow(18),
    apply_url: 'https://upsconline.nic.in',
    notification_url: 'https://upsc.gov.in/cds-2-2026',
  },
  {
    title: 'Combined Graduate Level (CGL) 2026',
    organization: 'Staff Selection Commission',
    board: 'SSC',
    category: 'central',
    status: 'open',
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    location_text: 'Pan India',
    lat: 28.6139, lon: 77.2090,
    posted_at: daysAgo(7),
    last_date: daysFromNow(35),
    apply_url: 'https://ssc.nic.in',
    notification_url: 'https://ssc.nic.in/cgl-2026',
  },
  {
    title: 'Multi-Tasking Staff (MTS) 2026',
    organization: 'Staff Selection Commission',
    board: 'SSC',
    category: 'central',
    status: 'open',
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    location_text: 'Pan India',
    lat: 28.6139, lon: 77.2090,
    posted_at: daysAgo(4),
    last_date: daysFromNow(45),
    apply_url: 'https://ssc.nic.in',
    notification_url: 'https://ssc.nic.in/mts-2026',
  },
  {
    title: 'Indian Forest Service (IFS) 2026',
    organization: 'Ministry of Environment',
    board: 'UPSC',
    category: 'central',
    status: 'upcoming',
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    location_text: 'Pan India',
    lat: 28.6139, lon: 77.2090,
    posted_at: daysAgo(2),
    last_date: daysFromNow(55),
    apply_url: 'https://upsconline.nic.in',
    notification_url: 'https://upsc.gov.in/ifs-2026',
  },

  // ── Railways (RRB) ─────────────────────────────────────────────────────────
  {
    title: 'Junior Engineer (Signal) – RRB Allahabad',
    organization: 'Indian Railways',
    board: 'RRB',
    category: 'central',
    status: 'open',
    state: 'Uttar Pradesh',
    district: 'Prayagraj',
    city: 'Prayagraj',
    location_text: 'Prayagraj, Uttar Pradesh',
    lat: 25.4358, lon: 81.8463,
    posted_at: daysAgo(9),
    last_date: daysFromNow(22),
    apply_url: 'https://rrbald.gov.in',
    notification_url: 'https://rrbald.gov.in/je-signal-2026',
  },
  {
    title: 'NTPC Graduate Level (RRB NTPC) 2026',
    organization: 'Indian Railways',
    board: 'RRB',
    category: 'central',
    status: 'open',
    state: 'Bihar',
    district: 'Patna',
    city: 'Patna',
    location_text: 'Patna, Bihar',
    lat: 25.5941, lon: 85.1376,
    posted_at: daysAgo(6),
    last_date: daysFromNow(28),
    apply_url: 'https://rrbcdg.gov.in',
    notification_url: 'https://rrbcdg.gov.in/ntpc-2026',
  },
  {
    title: 'Goods Guard – RRB Chennai',
    organization: 'Indian Railways',
    board: 'RRB',
    category: 'central',
    status: 'open',
    state: 'Tamil Nadu',
    district: 'Chennai',
    city: 'Chennai',
    location_text: 'Chennai, Tamil Nadu',
    lat: 13.0827, lon: 80.2707,
    posted_at: daysAgo(11),
    last_date: daysFromNow(12),
    apply_url: 'https://rrbchennai.gov.in',
    notification_url: 'https://rrbchennai.gov.in/guard-2026',
  },

  // ── Banking ────────────────────────────────────────────────────────────────
  {
    title: 'Probationary Officer (PO) – SBI',
    organization: 'State Bank of India',
    board: 'SBI',
    category: 'bank',
    status: 'open',
    state: 'Maharashtra',
    district: 'Mumbai',
    city: 'Mumbai',
    location_text: 'Pan India (HQ Mumbai)',
    lat: 18.9220, lon: 72.8347,
    posted_at: daysAgo(14),
    last_date: daysFromNow(8),
    apply_url: 'https://sbi.co.in/careers',
    notification_url: 'https://sbi.co.in/po-2026',
  },
  {
    title: 'Clerk (IBPS CRP Clerks XVI)',
    organization: 'IBPS (Multiple Banks)',
    board: 'IBPS',
    category: 'bank',
    status: 'open',
    state: 'Maharashtra',
    district: 'Mumbai',
    city: 'Mumbai',
    location_text: 'Pan India',
    lat: 19.0144, lon: 72.8479,
    posted_at: daysAgo(3),
    last_date: daysFromNow(38),
    apply_url: 'https://ibps.in',
    notification_url: 'https://ibps.in/crp-clerks-xvi',
  },
  {
    title: 'Specialist Officer (IT) – Bank of Baroda',
    organization: 'Bank of Baroda',
    board: 'BOB',
    category: 'bank',
    status: 'open',
    state: 'Gujarat',
    district: 'Vadodara',
    city: 'Vadodara',
    location_text: 'Vadodara, Gujarat',
    lat: 22.3072, lon: 73.1812,
    posted_at: daysAgo(5),
    last_date: daysFromNow(20),
    apply_url: 'https://bankofbaroda.in/careers',
    notification_url: 'https://bankofbaroda.in/so-it-2026',
  },

  // ── Defence ────────────────────────────────────────────────────────────────
  {
    title: 'Soldier (General Duty) – Indian Army',
    organization: 'Indian Army',
    board: 'ARO',
    category: 'defence',
    status: 'open',
    state: 'Punjab',
    district: 'Jalandhar',
    city: 'Jalandhar',
    location_text: 'Jalandhar, Punjab',
    lat: 31.3260, lon: 75.5762,
    posted_at: daysAgo(7),
    last_date: daysFromNow(30),
    apply_url: 'https://joinindianarmy.nic.in',
    notification_url: 'https://joinindianarmy.nic.in/soldier-gd-2026',
  },
  {
    title: 'Airmen (Group X & Y) – Indian Air Force',
    organization: 'Indian Air Force',
    board: 'AFCAT',
    category: 'defence',
    status: 'open',
    state: 'Delhi',
    district: 'New Delhi',
    city: 'New Delhi',
    location_text: 'Pan India',
    lat: 28.5665, lon: 77.1000,
    posted_at: daysAgo(4),
    last_date: daysFromNow(25),
    apply_url: 'https://airmenselection.cdac.in',
    notification_url: 'https://airmenselection.cdac.in/group-xy-2026',
  },

  // ── Karnataka ──────────────────────────────────────────────────────────────
  {
    title: 'First Division Assistant (FDA)',
    organization: 'Karnataka Government',
    board: 'KPSC',
    category: 'state',
    status: 'open',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    city: 'Bengaluru',
    location_text: 'Bengaluru, Karnataka',
    lat: 12.9716, lon: 77.5946,
    posted_at: daysAgo(8),
    last_date: daysFromNow(18),
    apply_url: 'https://kpsc.kar.nic.in',
    notification_url: 'https://kpsc.kar.nic.in/fda-2026',
  },
  {
    title: 'Village Administrative Officer (VAO)',
    organization: 'Karnataka Revenue Department',
    board: 'KPSC',
    category: 'state',
    status: 'upcoming',
    state: 'Karnataka',
    district: 'Mysuru',
    city: 'Mysuru',
    location_text: 'Mysuru, Karnataka',
    lat: 12.2958, lon: 76.6394,
    posted_at: daysAgo(1),
    last_date: daysFromNow(65),
    apply_url: 'https://kpsc.kar.nic.in',
    notification_url: 'https://kpsc.kar.nic.in/vao-2026',
  },

  // ── Tamil Nadu ─────────────────────────────────────────────────────────────
  {
    title: 'Group II (Deputy Collector)',
    organization: 'Tamil Nadu Government',
    board: 'TNPSC',
    category: 'state',
    status: 'open',
    state: 'Tamil Nadu',
    district: 'Chennai',
    city: 'Chennai',
    location_text: 'Chennai, Tamil Nadu',
    lat: 13.0827, lon: 80.2707,
    posted_at: daysAgo(10),
    last_date: daysFromNow(22),
    apply_url: 'https://tnpsc.gov.in',
    notification_url: 'https://tnpsc.gov.in/group2-2026',
  },
  {
    title: 'Combined Civil Services Exam IV (Group-IV)',
    organization: 'Tamil Nadu Government',
    board: 'TNPSC',
    category: 'state',
    status: 'open',
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    city: 'Coimbatore',
    location_text: 'Coimbatore, Tamil Nadu',
    lat: 11.0168, lon: 76.9558,
    posted_at: daysAgo(6),
    last_date: daysFromNow(32),
    apply_url: 'https://tnpsc.gov.in',
    notification_url: 'https://tnpsc.gov.in/group4-2026',
  },

  // ── Bihar ──────────────────────────────────────────────────────────────────
  {
    title: 'Bihar Judicial Services (BJS)',
    organization: 'Patna High Court',
    board: 'BPSC',
    category: 'state',
    status: 'open',
    state: 'Bihar',
    district: 'Patna',
    city: 'Patna',
    location_text: 'Patna, Bihar',
    lat: 25.6093, lon: 85.1235,
    posted_at: daysAgo(13),
    last_date: daysFromNow(7),
    apply_url: 'https://bpsc.bih.nic.in',
    notification_url: 'https://bpsc.bih.nic.in/bjs-2026',
  },
  {
    title: 'Bihar Teacher (BTET) – Primary',
    organization: 'Bihar School Examination Board',
    board: 'BSEB',
    category: 'state',
    status: 'open',
    state: 'Bihar',
    district: 'Muzaffarpur',
    city: 'Muzaffarpur',
    location_text: 'Muzaffarpur, Bihar',
    lat: 26.1209, lon: 85.3647,
    posted_at: daysAgo(5),
    last_date: daysFromNow(42),
    apply_url: 'https://bsebonline.com',
    notification_url: 'https://bsebonline.com/btet-2026',
  },

  // ── Madhya Pradesh ─────────────────────────────────────────────────────────
  {
    title: 'Patwari – MPPEB',
    organization: 'Revenue Department MP',
    board: 'MPPEB',
    category: 'state',
    status: 'open',
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    city: 'Bhopal',
    location_text: 'Bhopal, Madhya Pradesh',
    lat: 23.2599, lon: 77.4126,
    posted_at: daysAgo(9),
    last_date: daysFromNow(14),
    apply_url: 'https://peb.mp.gov.in',
    notification_url: 'https://peb.mp.gov.in/patwari-2026',
  },
  {
    title: 'Sub-Engineer (Civil) – MPPWD',
    organization: 'MP Public Works Department',
    board: 'MPPEB',
    category: 'state',
    status: 'upcoming',
    state: 'Madhya Pradesh',
    district: 'Indore',
    city: 'Indore',
    location_text: 'Indore, Madhya Pradesh',
    lat: 22.7196, lon: 75.8577,
    posted_at: daysAgo(2),
    last_date: daysFromNow(55),
    apply_url: 'https://peb.mp.gov.in',
    notification_url: 'https://peb.mp.gov.in/se-civil-2026',
  },

  // ── Gujarat ────────────────────────────────────────────────────────────────
  {
    title: 'Revenue Talati (Talati cum Mantri)',
    organization: 'Revenue Department Gujarat',
    board: 'GPSC',
    category: 'state',
    status: 'open',
    state: 'Gujarat',
    district: 'Ahmedabad',
    city: 'Ahmedabad',
    location_text: 'Ahmedabad, Gujarat',
    lat: 23.0225, lon: 72.5714,
    posted_at: daysAgo(11),
    last_date: daysFromNow(16),
    apply_url: 'https://ojas.gujarat.gov.in',
    notification_url: 'https://ojas.gujarat.gov.in/talati-2026',
  },
  {
    title: 'Dy. Section Officer (Class-II)',
    organization: 'Gujarat Government',
    board: 'GPSC',
    category: 'state',
    status: 'open',
    state: 'Gujarat',
    district: 'Surat',
    city: 'Surat',
    location_text: 'Surat, Gujarat',
    lat: 21.1702, lon: 72.8311,
    posted_at: daysAgo(4),
    last_date: daysFromNow(36),
    apply_url: 'https://gpsc.gujarat.gov.in',
    notification_url: 'https://gpsc.gujarat.gov.in/dso-2026',
  },

  // ── West Bengal ────────────────────────────────────────────────────────────
  {
    title: 'Clerkship Exam (WBP Clerk)',
    organization: 'West Bengal Police',
    board: 'WBPRB',
    category: 'state',
    status: 'open',
    state: 'West Bengal',
    district: 'Kolkata',
    city: 'Kolkata',
    location_text: 'Kolkata, West Bengal',
    lat: 22.5726, lon: 88.3639,
    posted_at: daysAgo(7),
    last_date: daysFromNow(19),
    apply_url: 'https://wbpolice.gov.in',
    notification_url: 'https://wbpolice.gov.in/clerk-2026',
  },
  {
    title: 'WBCS (Exe.) – Group A & B',
    organization: 'West Bengal Government',
    board: 'WBPSC',
    category: 'state',
    status: 'open',
    state: 'West Bengal',
    district: 'Howrah',
    city: 'Howrah',
    location_text: 'Howrah, West Bengal',
    lat: 22.5958, lon: 88.2636,
    posted_at: daysAgo(3),
    last_date: daysFromNow(28),
    apply_url: 'https://wbpsc.gov.in',
    notification_url: 'https://wbpsc.gov.in/wbcs-2026',
  },

  // ── Haryana ────────────────────────────────────────────────────────────────
  {
    title: 'Constable (Male & Female) – HSSC',
    organization: 'Haryana Police',
    board: 'HSSC',
    category: 'state',
    status: 'open',
    state: 'Haryana',
    district: 'Gurugram',
    city: 'Gurugram',
    location_text: 'Gurugram, Haryana',
    lat: 28.4595, lon: 77.0266,
    posted_at: daysAgo(8),
    last_date: daysFromNow(21),
    apply_url: 'https://hssc.gov.in',
    notification_url: 'https://hssc.gov.in/constable-2026',
  },
  {
    title: 'Naib Tehsildar – HPSC',
    organization: 'Haryana Revenue Department',
    board: 'HPSC',
    category: 'state',
    status: 'upcoming',
    state: 'Haryana',
    district: 'Faridabad',
    city: 'Faridabad',
    location_text: 'Faridabad, Haryana',
    lat: 28.4082, lon: 77.3178,
    posted_at: daysAgo(1),
    last_date: daysFromNow(70),
    apply_url: 'https://hpsc.gov.in',
    notification_url: 'https://hpsc.gov.in/naib-tehsildar-2026',
  },

  // ── Andhra Pradesh ─────────────────────────────────────────────────────────
  {
    title: 'Group-I Services (Deputy Collector)',
    organization: 'Andhra Pradesh Government',
    board: 'APPSC',
    category: 'state',
    status: 'open',
    state: 'Andhra Pradesh',
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    location_text: 'Visakhapatnam, Andhra Pradesh',
    lat: 17.6868, lon: 83.2185,
    posted_at: daysAgo(12),
    last_date: daysFromNow(17),
    apply_url: 'https://psc.ap.gov.in',
    notification_url: 'https://psc.ap.gov.in/group1-2026',
  },

  // ── Telangana ──────────────────────────────────────────────────────────────
  {
    title: 'Group-II (Assistant Section Officer)',
    organization: 'Telangana Government',
    board: 'TSPSC',
    category: 'state',
    status: 'open',
    state: 'Telangana',
    district: 'Hyderabad',
    city: 'Hyderabad',
    location_text: 'Hyderabad, Telangana',
    lat: 17.3850, lon: 78.4867,
    posted_at: daysAgo(6),
    last_date: daysFromNow(24),
    apply_url: 'https://tspsc.gov.in',
    notification_url: 'https://tspsc.gov.in/group2-2026',
  },
  {
    title: 'Polytechnic Lecturer (Electrical)',
    organization: 'Telangana Education Department',
    board: 'TSPSC',
    category: 'state',
    status: 'upcoming',
    state: 'Telangana',
    district: 'Warangal',
    city: 'Warangal',
    location_text: 'Warangal, Telangana',
    lat: 17.9784, lon: 79.5941,
    posted_at: daysAgo(2),
    last_date: daysFromNow(48),
    apply_url: 'https://tspsc.gov.in',
    notification_url: 'https://tspsc.gov.in/poly-lect-2026',
  },

  // ── PSU / Central PSE ──────────────────────────────────────────────────────
  {
    title: 'Graduate Apprentice – BHEL',
    organization: 'Bharat Heavy Electricals Ltd',
    board: 'BHEL',
    category: 'psu',
    status: 'open',
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    city: 'Bhopal',
    location_text: 'Bhopal, Madhya Pradesh',
    lat: 23.2260, lon: 77.4018,
    posted_at: daysAgo(5),
    last_date: daysFromNow(33),
    apply_url: 'https://bhel.com/careers',
    notification_url: 'https://bhel.com/apprentice-2026',
  },
  {
    title: 'Junior Associate (Customer Support) – SBI',
    organization: 'State Bank of India',
    board: 'SBI',
    category: 'bank',
    status: 'closed',
    state: 'Uttar Pradesh',
    district: 'Kanpur',
    city: 'Kanpur',
    location_text: 'Kanpur, Uttar Pradesh',
    lat: 26.4499, lon: 80.3319,
    posted_at: daysAgo(30),
    last_date: daysAgo(5),
    apply_url: 'https://sbi.co.in/careers',
    notification_url: 'https://sbi.co.in/ja-2026',
  },
  {
    title: 'Executive (Finance) – ONGC',
    organization: 'Oil & Natural Gas Corporation',
    board: 'ONGC',
    category: 'psu',
    status: 'open',
    state: 'Gujarat',
    district: 'Surat',
    city: 'Surat',
    location_text: 'Surat, Gujarat',
    lat: 21.1600, lon: 72.8400,
    posted_at: daysAgo(4),
    last_date: daysFromNow(26),
    apply_url: 'https://ongcindia.com',
    notification_url: 'https://ongcindia.com/exec-finance-2026',
  },
  {
    title: 'Management Trainee (Technical) – SAIL',
    organization: 'Steel Authority of India Ltd',
    board: 'SAIL',
    category: 'psu',
    status: 'open',
    state: 'Jharkhand',
    district: 'Bokaro',
    city: 'Bokaro',
    location_text: 'Bokaro Steel City, Jharkhand',
    lat: 23.6693, lon: 86.1511,
    posted_at: daysAgo(3),
    last_date: daysFromNow(40),
    apply_url: 'https://sail.co.in/careers',
    notification_url: 'https://sail.co.in/mt-tech-2026',
  },
];

async function seed() {
  const client = await pool.connect();
  try {
    console.log('Starting seed: inserting', JOBS.length, 'jobs…');

    for (const job of JOBS) {
      await client.query(
        `INSERT INTO jobs (
           title, organization, board, category, status,
           apply_url, notification_url,
           state, district, city, location_text, lat, lon,
           posted_at, last_date
         ) VALUES (
           $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15
         )
         ON CONFLICT DO NOTHING`,
        [
          job.title,
          job.organization || null,
          job.board || null,
          job.category || null,
          job.status || 'open',
          job.apply_url || null,
          job.notification_url || null,
          job.state || null,
          job.district || null,
          job.city || null,
          job.location_text || null,
          job.lat || null,
          job.lon || null,
          job.posted_at || null,
          job.last_date || null,
        ]
      );
    }

    const count = await client.query('SELECT COUNT(*) FROM jobs');
    console.log('✅ Seed complete. Total jobs in table:', count.rows[0].count);
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  } finally {
    client.release();
    await pool.end();
  }
}

seed();
